### ISSUE TITLE
FCI Minor issues

### ISSUE THREAD

**Issue by justusc** [m-a-d-n-e-s-s/madness#10]
Google Code issue 28

Reported by burnus, Dec 1, 2010

That's all with regards to: m-a-d-n-e-s-s-read-only/src/apps/moldft/fci 

a. The following compile time warning is shown:

```
fci_hami.F:33.39:

      call fci_hamil2(hamil,work(ih),g,work(io),nonemx,
                                       1
Warning: Type mismatch in argument 'ionel' at (1); passed REAL(8) to INTEGER(4)
```

b. In the GNUmakefile:

Please do not use -malign-double or -mno-align-double: The option changes the ABI and will only work if one compiles also all libraries with that option (libgfortran, libc, ...). If one does not, the chances are extremely high that one gets strange segfaults with a differently compiled libgfortran. Cf. http://gcc.gnu.org/onlinedocs/gcc/i386-and-x86_002d64-Options.html

Using "-march=native" is a much more useful option: It optimizes the binary for the system being compiled. [Or the option -flto, which adds inter-file optimization (requires GCC 4.5 or newer).]

c. There is a "+" missing in doc/matrixelements.tex without the verbatim text extends to far:

```
--- doc/matrixelements.tex      (revision 2017)
+++ doc/matrixelements.tex      (working copy)
@@ -926,7 +926,7 @@
 (Section \ref{sec:fcireadvectors}).

 The input integrals are stored as
-\verb+h(ij)+=$h_{ij}$ and \verb+g(ij,kl)=$(ij|kl)$, with $i \geq j$,
+\verb+h(ij)+=$h_{ij}$ and \verb+g(ij,kl)+=$(ij|kl)$, with $i \geq j$,
 $k \geq l$, \verb+ij+=$i(i-1)/2$, and \verb+kl+=$k(k-1)/2+l$.  Have a
 look at \verb+fci_load.F+ to see how an ASCII list of integrals are
 read in an inserted into these arrays in the test program.
```

**Comment by naromero77** [comment]
Is this issue still relevant?
