### ISSUE TITLE
Configure incorrectly concludes that I'm on a BGP or a BGQ

### ISSUE THREAD

**Issue by wsttiger** [m-a-d-n-e-s-s/madness#102]
Configure sets the HAVE_IBMBGP and HAVE_IBMBGQ define variables when I configure on the IACS cluster Handy.

After running "autoreconf", I run configure as follows:

MPICC="mpiicc" MPICXX="mpiicpc" ./configure CXXFLAGS="-O2"

I'm using both Intel compiler and Intel MPI (v. 5.0).

**Comment by naromero77** [comment]
Scott, can you let us know if this is still an issue? Thanks.
