### ISSUE TITLE
Reproducibility problem in moldft, likely due to race condition

### ISSUE THREAD

**Issue by lratcliff** [m-a-d-n-e-s-s/madness#103]
Two consecutive runs of moldft can have very different convergence behaviour - it starts out the same but by the second or third iteration the energies are very different.  They end up at very similar energies, but the differences are such that one calculation might take twice as long as another.
It occurs for both LDA (internal rather than libxc) and HF, and it's worse when starting from sto-3g basis rather than 6-31g.  I'm running on my desktop without Elemental, compiled with gcc.  If I run with MAD_NUM_THREADS=1 rather than 12 it behaves consistently, so I assume there's a race condition somewhere. Here's the input I used:

dft
  xc hf
  aobasis sto-3g
end

geometry
 Na      1.31092303931025942E+01  1.31092303931026493E+01  1.31092303931017025E+01
 Cl      1.78689078546959657E+01  1.78689078546958307E+01  1.78689078546942923E+01
end

**Comment by naromero77** [comment]
Is this still an issue?

**Comment by robertjharrison** [comment]
Not in any of my tests, but I have not had opportunity to test on large
processor counts.

On Sun, Feb 8, 2015 at 2:06 PM, Nichols A. Romero <notifications@github.com>
wrote:

> Is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/103#issuecomment-73425756>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by robertjharrison** [comment]
All tests current seem reproducible.
