### ISSUE TITLE
adding default options for paths MRA_DATA_DIR and basis sets

### ISSUE THREAD

**Issue by v4m4** [m-a-d-n-e-s-s/madness#107]
I suggest to add default paths (for example mra and basis sets) to libMADmra.a and moldft, such adding them as an environment variable are just optional

**Comment by naromero77** [comment]
Is this still an issue?

**Comment by naromero77** [comment]
There is a MRA_CHEMDATA_DIR and MRA_DATA_DIR each with default paths. I believe that this issue can be closed.
