### ISSUE TITLE
testdiff3D: !!!!!!MMMAAADDDNNNEEESSSSSS:::   HHHuuunnnggg   qqquuueeeuuueee???

### ISSUE THREAD

**Issue by jeffhammond** [m-a-d-n-e-s-s/madness#111]
```
raguerra-mobl:build-intel jrhammon$ cat ./src/madness/mra/testdiff3D.log
MADNESS runtime initialized with 3 threads in the pool and affinity -1 -1 -1

--------------------------------------------
   MADNESS 0.9 multiresolution suite
--------------------------------------------

   number of processors ... 1
    processor frequency ... 2.299850e+09
            host system ... darwin13.4.0
          configured by ... jrhammon
          configured on ... jrhammon-mac01.ra.intel.com
          configured at ... Wed Dec 17 09:51:11 PST 2014
                    CXX ... icpc
               CXXFLAGS ...  -O3 -Wall -diag-disable remark,279,654,1125  -ip -no-prec-div -mkl=sequential -ansi -xHOST -std=c++0x
             tuning for ... core2
              Intel TBB ... yes 
               compiled ... 10:20:02  on  Dec 17 2014
Unorm 1.039087919140e+02
t


!!MADNESS: Hung queue?
!!!!!!MMMAAADDDNNNEEESSSSSS:::   HHHuuunnnggg   qqquuueeeuuueee???


!!MADNESS: Hung queue?
!!!!MMAA!DD!NNMEEASSDSSN::E  SHHSuu:nn ggH  uqqnuugee uuqeeu??e

ue?
!!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS: !!H!!uMMnAAgDD NNqEEuSSeSSu::e  ?HH
uunngg  qquueeuuee??

!!MADNESS: Hung queue?
!!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with 5 pending task(s)
libc++abi.dylib: terminating with uncaught exception of type madness::MadnessException: ThreadPool::await() timeout
```

**Comment by naromero77** [comment]
I believe that I am seeing the same problem on BG/Q.  I just ran the NaCl on 1 MPI task for iter 1 and I get:
Iteration 0 at time 35.4s

timer:       Make densities     0.38s     0.38s
timer:       Load balancing     0.00s     0.00s
timer:       Nuclear energy     0.03s     0.03s
timer:              Coulomb     1.77s     1.77s
timer:            DFT setup     0.01s     0.01s
 !!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS: Hung queue?
!!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with 1 pending task(s)
MadnessException : msg=ThreadPool::await() timeout : value=1 : line=1081 : function=await : filename='../../../src/madness/world/worldthread.h'

Older versions of MADNESS seem to be OK.

**Comment by robertjharrison** [comment]
Was this with libxc or without?

Without presently appears to not work (generates NaNs which causes infinite
refinement).

On Sun, Feb 8, 2015 at 2:08 PM, Nichols A. Romero <notifications@github.com>
wrote:

> I believe that I am seeing the same problem on BG/Q. I just ran the NaCl
> on 1 MPI task for iter 1 and I get:
> Iteration 0 at time 35.4s
>
> timer: Make densities 0.38s 0.38s
> timer: Load balancing 0.00s 0.00s
> timer: Nuclear energy 0.03s 0.03s
> timer: Coulomb 1.77s 1.77s
> timer: DFT setup 0.01s 0.01s
> !!MADNESS: Hung queue?
> !!MADNESS: Hung queue?
> !!MADNESS: Hung queue?
> !!MADNESS: Hung queue?
> !!MADNESS: Hung queue?
> !!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with 1
> pending task(s)
> MadnessException : msg=ThreadPool::await() timeout : value=1 : line=1081 :
> function=await : filename='../../../src/madness/world/worldthread.h'
>
> Older versions of MADNESS seem to be OK.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73425859>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by jeffhammond** [comment]
I don't link with libxc. If it's necessary to run correctly here, we should
add appropriate ifdef etc.

On Sunday, February 8, 2015, robertjharrison <notifications@github.com>
wrote:

> Was this with libxc or without?
>
> Without presently appears to not work (generates NaNs which causes infinite
> refinement).
>
> On Sun, Feb 8, 2015 at 2:08 PM, Nichols A. Romero <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I believe that I am seeing the same problem on BG/Q. I just ran the NaCl
> > on 1 MPI task for iter 1 and I get:
> > Iteration 0 at time 35.4s
> >
> > timer: Make densities 0.38s 0.38s
> > timer: Load balancing 0.00s 0.00s
> > timer: Nuclear energy 0.03s 0.03s
> > timer: Coulomb 1.77s 1.77s
> > timer: DFT setup 0.01s 0.01s
> > !!MADNESS: Hung queue?
> > !!MADNESS: Hung queue?
> > !!MADNESS: Hung queue?
> > !!MADNESS: Hung queue?
> > !!MADNESS: Hung queue?
> > !!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with 1
> > pending task(s)
> > MadnessException : msg=ThreadPool::await() timeout : value=1 : line=1081
> :
> > function=await : filename='../../../src/madness/world/worldthread.h'
> >
> > Older versions of MADNESS seem to be OK.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73425859>
> > .
> >
>
>
>
> --
> Robert J. Harrison
> tel: 865-272-9262
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73452121>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by robertjharrison** [comment]
It's a bug that needs fixing since I think many people will just want lda
and not want to bother w libxc.

**Comment by naromero77** [comment]
It looks like there is some bug that got introduced after Christmas. It was
present as of Jan. 30. Going back further.

On Sun, Feb 8, 2015 at 9:46 PM, robertjharrison <notifications@github.com>
wrote:

> It's a bug that needs fixing since I think many people will just want lda
> and not want to bother w libxc.
> On Feb 8, 2015 10:44 PM, "Jeff Hammond" <notifications@github.com> wrote:
>
> > I don't link with libxc. If it's necessary to run correctly here, we
> should
> > add appropriate ifdef etc.
> >
> > On Sunday, February 8, 2015, robertjharrison <notifications@github.com>
> > wrote:
> >
> > > Was this with libxc or without?
> > >
> > > Without presently appears to not work (generates NaNs which causes
> > infinite
> > > refinement).
> > >
> > > On Sun, Feb 8, 2015 at 2:08 PM, Nichols A. Romero <
> > > notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > >
> > > > I believe that I am seeing the same problem on BG/Q. I just ran the
> > NaCl
> > > > on 1 MPI task for iter 1 and I get:
> > > > Iteration 0 at time 35.4s
> > > >
> > > > timer: Make densities 0.38s 0.38s
> > > > timer: Load balancing 0.00s 0.00s
> > > > timer: Nuclear energy 0.03s 0.03s
> > > > timer: Coulomb 1.77s 1.77s
> > > > timer: DFT setup 0.01s 0.01s
> > > > !!MADNESS: Hung queue?
> > > > !!MADNESS: Hung queue?
> > > > !!MADNESS: Hung queue?
> > > > !!MADNESS: Hung queue?
> > > > !!MADNESS: Hung queue?
> > > > !!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with 1
> > > > pending task(s)
> > > > MadnessException : msg=ThreadPool::await() timeout : value=1 :
> > line=1081
> > > :
> > > > function=await : filename='../../../src/madness/world/worldthread.h'
> > > >
> > > > Older versions of MADNESS seem to be OK.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73425859>
> > > > .
> > > >
> > >
> > >
> > >
> > > --
> > > Robert J. Harrison
> > > tel: 865-272-9262
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73452121>
> > > .
> > >
> >
> >
> > --
> > Jeff Hammond
> > jeff.science@gmail.com
> > http://jeffhammond.github.io/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453671>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453774>
> .
>



-- 
Nichols A. Romero, Ph.D.

**Comment by naromero77** [comment]
BG/Qs are down for maintenance already. Also, looks like I will be starting
paternity leave today.

At first I thought the issue was something in world lib, but the problem
was also present in Jan. 27.

My next step was to check this version from Dec. 28 (includes my merge, but
not Robert's compress changes). I got as far as compiling, but the job did
not get a chance to run before the preventive maintenance.


On Sun, Feb 8, 2015 at 9:47 PM, Nichols A. Romero <naromero@gmail.com>
wrote:

> It looks like there is some bug that got introduced after Christmas. It
> was present as of Jan. 30. Going back further.
>
> On Sun, Feb 8, 2015 at 9:46 PM, robertjharrison <notifications@github.com>
> wrote:
>
>> It's a bug that needs fixing since I think many people will just want lda
>> and not want to bother w libxc.
>> On Feb 8, 2015 10:44 PM, "Jeff Hammond" <notifications@github.com> wrote:
>>
>> > I don't link with libxc. If it's necessary to run correctly here, we
>> should
>> > add appropriate ifdef etc.
>> >
>> > On Sunday, February 8, 2015, robertjharrison <notifications@github.com>
>> > wrote:
>> >
>> > > Was this with libxc or without?
>> > >
>> > > Without presently appears to not work (generates NaNs which causes
>> > infinite
>> > > refinement).
>> > >
>> > > On Sun, Feb 8, 2015 at 2:08 PM, Nichols A. Romero <
>> > > notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
>> > > wrote:
>> > >
>> > > > I believe that I am seeing the same problem on BG/Q. I just ran the
>> > NaCl
>> > > > on 1 MPI task for iter 1 and I get:
>> > > > Iteration 0 at time 35.4s
>> > > >
>> > > > timer: Make densities 0.38s 0.38s
>> > > > timer: Load balancing 0.00s 0.00s
>> > > > timer: Nuclear energy 0.03s 0.03s
>> > > > timer: Coulomb 1.77s 1.77s
>> > > > timer: DFT setup 0.01s 0.01s
>> > > > !!MADNESS: Hung queue?
>> > > > !!MADNESS: Hung queue?
>> > > > !!MADNESS: Hung queue?
>> > > > !!MADNESS: Hung queue?
>> > > > !!MADNESS: Hung queue?
>> > > > !!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with 1
>> > > > pending task(s)
>> > > > MadnessException : msg=ThreadPool::await() timeout : value=1 :
>> > line=1081
>> > > :
>> > > > function=await : filename='../../../src/madness/world/worldthread.h'
>> > > >
>> > > > Older versions of MADNESS seem to be OK.
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub
>> > > > <
>> > >
>> >
>> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73425859
>> >
>> > > > .
>> > > >
>> > >
>> > >
>> > >
>> > > --
>> > > Robert J. Harrison
>> > > tel: 865-272-9262
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73452121
>> >
>> > > .
>> > >
>> >
>> >
>> > --
>> > Jeff Hammond
>> > jeff.science@gmail.com
>> > http://jeffhammond.github.io/
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453671
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453774>
>> .
>>
>
>
>
> --
> Nichols A. Romero, Ph.D.
>
>


-- 
Nichols A. Romero, Ph.D.

**Comment by jeffhammond** [comment]
I am going to see if it fixes my issues on x86.  I assume one of you compatriots will be able to verify relatively soon.

Congrats on being a dad :-)

**Comment by robertjharrison** [comment]
Nick ... super cool ... my very best to you and your family.

Robert

On Mon, Feb 9, 2015 at 10:04 AM, Nichols A. Romero <notifications@github.com
> wrote:

> BG/Qs are down for maintenance already. Also, looks like I will be starting
> paternity leave today.
>
> At first I thought the issue was something in world lib, but the problem
> was also present in Jan. 27.
>
> My next step was to check this version from Dec. 28 (includes my merge, but
> not Robert's compress changes). I got as far as compiling, but the job did
> not get a chance to run before the preventive maintenance.
>
>
> On Sun, Feb 8, 2015 at 9:47 PM, Nichols A. Romero <naromero@gmail.com>
> wrote:
>
>
> > It looks like there is some bug that got introduced after Christmas. It
> > was present as of Jan. 30. Going back further.
> >
> > On Sun, Feb 8, 2015 at 9:46 PM, robertjharrison <
> notifications@github.com>
> > wrote:
> >
> >> It's a bug that needs fixing since I think many people will just want
> lda
> >> and not want to bother w libxc.
> >> On Feb 8, 2015 10:44 PM, "Jeff Hammond" <notifications@github.com>
> wrote:
> >>
> >> > I don't link with libxc. If it's necessary to run correctly here, we
> >> should
> >> > add appropriate ifdef etc.
> >> >
> >> > On Sunday, February 8, 2015, robertjharrison <
> notifications@github.com>
> >> > wrote:
> >> >
> >> > > Was this with libxc or without?
> >> > >
> >> > > Without presently appears to not work (generates NaNs which causes
> >> > infinite
> >> > > refinement).
> >> > >
> >> > > On Sun, Feb 8, 2015 at 2:08 PM, Nichols A. Romero <
> >> > > notifications@github.com
> >> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> >> > > wrote:
> >> > >
> >> > > > I believe that I am seeing the same problem on BG/Q. I just ran
> the
> >> > NaCl
> >> > > > on 1 MPI task for iter 1 and I get:
> >> > > > Iteration 0 at time 35.4s
> >> > > >
> >> > > > timer: Make densities 0.38s 0.38s
> >> > > > timer: Load balancing 0.00s 0.00s
> >> > > > timer: Nuclear energy 0.03s 0.03s
> >> > > > timer: Coulomb 1.77s 1.77s
> >> > > > timer: DFT setup 0.01s 0.01s
> >> > > > !!MADNESS: Hung queue?
> >> > > > !!MADNESS: Hung queue?
> >> > > > !!MADNESS: Hung queue?
> >> > > > !!MADNESS: Hung queue?
> >> > > > !!MADNESS: Hung queue?
> >> > > > !!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with
> 1
> >> > > > pending task(s)
> >> > > > MadnessException : msg=ThreadPool::await() timeout : value=1 :
> >> > line=1081
> >> > > :
> >> > > > function=await :
> filename='../../../src/madness/world/worldthread.h'
> >> > > >
> >> > > > Older versions of MADNESS seem to be OK.
> >> > > >
> >> > > > —
> >> > > > Reply to this email directly or view it on GitHub
> >> > > > <
> >> > >
> >> >
> >>
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73425859
> >> >
> >> > > > .
> >> > > >
> >> > >
> >> > >
> >> > >
> >> > > --
> >> > > Robert J. Harrison
> >> > > tel: 865-272-9262
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <
> >> >
> >>
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73452121
> >> >
> >> > > .
> >> > >
> >> >
> >> >
> >> > --
> >> > Jeff Hammond
> >> > jeff.science@gmail.com
> >> > http://jeffhammond.github.io/
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453671
> >> >
> >>
> >> > .
> >> >
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453774>
> >> .
> >>
> >
> >
> >
> > --
> > Nichols A. Romero, Ph.D.
> >
> >
>
>
> --
> Nichols A. Romero, Ph.D.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73522994>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by naromero77** [comment]
Thanks Robert.

Now that I am back home, I am investigating this further.

If I run this on 2 nodes, I get this error instead:
MadnessException : msg=failed acquiring mutex : value=22 : line=119 :
function=l
ock : filename='../../../src/madness/world/worldmutex.h'


On Mon, Feb 9, 2015 at 9:20 AM, robertjharrison <notifications@github.com>
wrote:

> Nick ... super cool ... my very best to you and your family.
>
> Robert
>
>
> On Mon, Feb 9, 2015 at 10:04 AM, Nichols A. Romero <
> notifications@github.com
> > wrote:
>
> > BG/Qs are down for maintenance already. Also, looks like I will be
> starting
> > paternity leave today.
> >
> > At first I thought the issue was something in world lib, but the problem
> > was also present in Jan. 27.
> >
> > My next step was to check this version from Dec. 28 (includes my merge,
> but
> > not Robert's compress changes). I got as far as compiling, but the job
> did
> > not get a chance to run before the preventive maintenance.
> >
> >
> > On Sun, Feb 8, 2015 at 9:47 PM, Nichols A. Romero <naromero@gmail.com>
> > wrote:
> >
> >
> > > It looks like there is some bug that got introduced after Christmas. It
> > > was present as of Jan. 30. Going back further.
> > >
> > > On Sun, Feb 8, 2015 at 9:46 PM, robertjharrison <
> > notifications@github.com>
> > > wrote:
> > >
> > >> It's a bug that needs fixing since I think many people will just want
> > lda
> > >> and not want to bother w libxc.
> > >> On Feb 8, 2015 10:44 PM, "Jeff Hammond" <notifications@github.com>
> > wrote:
> > >>
> > >> > I don't link with libxc. If it's necessary to run correctly here, we
> > >> should
> > >> > add appropriate ifdef etc.
> > >> >
> > >> > On Sunday, February 8, 2015, robertjharrison <
> > notifications@github.com>
> > >> > wrote:
> > >> >
> > >> > > Was this with libxc or without?
> > >> > >
> > >> > > Without presently appears to not work (generates NaNs which causes
> > >> > infinite
> > >> > > refinement).
> > >> > >
> > >> > > On Sun, Feb 8, 2015 at 2:08 PM, Nichols A. Romero <
> > >> > > notifications@github.com
> > >> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > >> > > wrote:
> > >> > >
> > >> > > > I believe that I am seeing the same problem on BG/Q. I just ran
> > the
> > >> > NaCl
> > >> > > > on 1 MPI task for iter 1 and I get:
> > >> > > > Iteration 0 at time 35.4s
> > >> > > >
> > >> > > > timer: Make densities 0.38s 0.38s
> > >> > > > timer: Load balancing 0.00s 0.00s
> > >> > > > timer: Nuclear energy 0.03s 0.03s
> > >> > > > timer: Coulomb 1.77s 1.77s
> > >> > > > timer: DFT setup 0.01s 0.01s
> > >> > > > !!MADNESS: Hung queue?
> > >> > > > !!MADNESS: Hung queue?
> > >> > > > !!MADNESS: Hung queue?
> > >> > > > !!MADNESS: Hung queue?
> > >> > > > !!MADNESS: Hung queue?
> > >> > > > !!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence()
> with
> > 1
> > >> > > > pending task(s)
> > >> > > > MadnessException : msg=ThreadPool::await() timeout : value=1 :
> > >> > line=1081
> > >> > > :
> > >> > > > function=await :
> > filename='../../../src/madness/world/worldthread.h'
> > >> > > >
> > >> > > > Older versions of MADNESS seem to be OK.
> > >> > > >
> > >> > > > —
> > >> > > > Reply to this email directly or view it on GitHub
> > >> > > > <
> > >> > >
> > >> >
> > >>
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73425859
> > >> >
> > >> > > > .
> > >> > > >
> > >> > >
> > >> > >
> > >> > >
> > >> > > --
> > >> > > Robert J. Harrison
> > >> > > tel: 865-272-9262
> > >> > >
> > >> > > —
> > >> > > Reply to this email directly or view it on GitHub
> > >> > > <
> > >> >
> > >>
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73452121
> > >> >
> > >> > > .
> > >> > >
> > >> >
> > >> >
> > >> > --
> > >> > Jeff Hammond
> > >> > jeff.science@gmail.com
> > >> > http://jeffhammond.github.io/
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <
> > >>
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453671
> > >> >
> > >>
> > >> > .
> > >> >
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453774>
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > Nichols A. Romero, Ph.D.
> > >
> > >
> >
> >
> > --
> > Nichols A. Romero, Ph.D.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73522994>
> > .
> >
>
>
>
> --
> Robert J. Harrison
> tel: 865-272-9262
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73525912>
> .
>



-- 
Nichols A. Romero, Ph.D.

**Comment by robertjharrison** [comment]
I will start separate threads to continue the discussion separately for
each problem

On Wed, Feb 11, 2015 at 11:13 PM, Nichols A. Romero <
notifications@github.com> wrote:

> Thanks Robert.
>
> Now that I am back home, I am investigating this further.
>
> If I run this on 2 nodes, I get this error instead:
> MadnessException : msg=failed acquiring mutex : value=22 : line=119 :
> function=l
> ock : filename='../../../src/madness/world/worldmutex.h'
>
>
> On Mon, Feb 9, 2015 at 9:20 AM, robertjharrison <notifications@github.com>
> wrote:
>
>
> > Nick ... super cool ... my very best to you and your family.
> >
> > Robert
> >
> >
> > On Mon, Feb 9, 2015 at 10:04 AM, Nichols A. Romero <
> > notifications@github.com
> > > wrote:
> >
> > > BG/Qs are down for maintenance already. Also, looks like I will be
> > starting
> > > paternity leave today.
> > >
> > > At first I thought the issue was something in world lib, but the
> problem
> > > was also present in Jan. 27.
> > >
> > > My next step was to check this version from Dec. 28 (includes my merge,
> > but
> > > not Robert's compress changes). I got as far as compiling, but the job
> > did
> > > not get a chance to run before the preventive maintenance.
> > >
> > >
> > > On Sun, Feb 8, 2015 at 9:47 PM, Nichols A. Romero <naromero@gmail.com>
> > > wrote:
> > >
> > >
> > > > It looks like there is some bug that got introduced after Christmas.
> It
> > > > was present as of Jan. 30. Going back further.
> > > >
> > > > On Sun, Feb 8, 2015 at 9:46 PM, robertjharrison <
> > > notifications@github.com>
> > > > wrote:
> > > >
> > > >> It's a bug that needs fixing since I think many people will just
> want
> > > lda
> > > >> and not want to bother w libxc.
> > > >> On Feb 8, 2015 10:44 PM, "Jeff Hammond" <notifications@github.com>
> > > wrote:
> > > >>
> > > >> > I don't link with libxc. If it's necessary to run correctly here,
> we
> > > >> should
> > > >> > add appropriate ifdef etc.
> > > >> >
> > > >> > On Sunday, February 8, 2015, robertjharrison <
> > > notifications@github.com>
> > > >> > wrote:
> > > >> >
> > > >> > > Was this with libxc or without?
> > > >> > >
> > > >> > > Without presently appears to not work (generates NaNs which
> causes
> > > >> > infinite
> > > >> > > refinement).
> > > >> > >
> > > >> > > On Sun, Feb 8, 2015 at 2:08 PM, Nichols A. Romero <
> > > >> > > notifications@github.com
> > > >> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > >> > > wrote:
> > > >> > >
> > > >> > > > I believe that I am seeing the same problem on BG/Q. I just
> ran
> > > the
> > > >> > NaCl
> > > >> > > > on 1 MPI task for iter 1 and I get:
> > > >> > > > Iteration 0 at time 35.4s
> > > >> > > >
> > > >> > > > timer: Make densities 0.38s 0.38s
> > > >> > > > timer: Load balancing 0.00s 0.00s
> > > >> > > > timer: Nuclear energy 0.03s 0.03s
> > > >> > > > timer: Coulomb 1.77s 1.77s
> > > >> > > > timer: DFT setup 0.01s 0.01s
> > > >> > > > !!MADNESS: Hung queue?
> > > >> > > > !!MADNESS: Hung queue?
> > > >> > > > !!MADNESS: Hung queue?
> > > >> > > > !!MADNESS: Hung queue?
> > > >> > > > !!MADNESS: Hung queue?
> > > >> > > > !!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence()
> > with
> > > 1
> > > >> > > > pending task(s)
> > > >> > > > MadnessException : msg=ThreadPool::await() timeout : value=1 :
> > > >> > line=1081
> > > >> > > :
> > > >> > > > function=await :
> > > filename='../../../src/madness/world/worldthread.h'
> > > >> > > >
> > > >> > > > Older versions of MADNESS seem to be OK.
> > > >> > > >
> > > >> > > > —
> > > >> > > > Reply to this email directly or view it on GitHub
> > > >> > > > <
> > > >> > >
> > > >> >
> > > >>
> > >
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73425859
> > > >> >
> > > >> > > > .
> > > >> > > >
> > > >> > >
> > > >> > >
> > > >> > >
> > > >> > > --
> > > >> > > Robert J. Harrison
> > > >> > > tel: 865-272-9262
> > > >> > >
> > > >> > > —
> > > >> > > Reply to this email directly or view it on GitHub
> > > >> > > <
> > > >> >
> > > >>
> > >
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73452121
> > > >> >
> > > >> > > .
> > > >> > >
> > > >> >
> > > >> >
> > > >> > --
> > > >> > Jeff Hammond
> > > >> > jeff.science@gmail.com
> > > >> > http://jeffhammond.github.io/
> > > >> >
> > > >> > —
> > > >> > Reply to this email directly or view it on GitHub
> > > >> > <
> > > >>
> > >
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453671
> > > >> >
> > > >>
> > > >> > .
> > > >> >
> > > >>
> > > >> —
> > > >> Reply to this email directly or view it on GitHub
> > > >> <
> > >
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73453774>
> > > >> .
> > > >>
> > > >
> > > >
> > > >
> > > > --
> > > > Nichols A. Romero, Ph.D.
> > > >
> > > >
> > >
> > >
> > > --
> > > Nichols A. Romero, Ph.D.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73522994>
> > > .
> > >
> >
> >
> >
> > --
> > Robert J. Harrison
> > tel: 865-272-9262
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-73525912>
> > .
> >
>
>
>
> --
> Nichols A. Romero, Ph.D.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/111#issuecomment-74014891>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by robertjharrison** [comment]
nan fixed
