### ISSUE TITLE
MPI_Irecv truncation error

### ISSUE THREAD

**Issue by jeffhammond** [m-a-d-n-e-s-s/madness#113]
Configure:

```
../configure MPICC=/opt/mpich/dev/intel/debug/bin/mpicc \
MPICXX=/opt/mpich/dev/intel/debug/bin/mpicxx \
--with-tbb=/opt/intel/composerxe/tbb --with-mkl \
--prefix=$HOME/Work/MADNESS/install-intel \
--enable-optimal=intel
```

Try to run with more than 1 process per node (1 is fine):

```
/opt/mpich/dev/intel/debug/bin/mpirun -n 2 ./src/madness/mra/testsuite.mpi
```

See this error:

```
Test multiplying random functions
Fatal error in MPI_Irecv: Message truncated, error stack:
MPI_Irecv(153)......................: MPI_Irecv(buf=0x5ba4040, count=8, MPI_BYTE, src=1, tag=2265, MPI_COMM_WORLD, request=0x7fff0594d124) failed
MPIDI_CH3U_Request_unpack_uebuf(611): Message truncated; 16 bytes received but buffer size is 8
```

Details:

```
icc -v
icc version 15.0.1 (gcc version 4.9.0 compatibility)
```

```
/opt/mpich/dev/intel/debug/bin/mpichversion 
MPICH Version:      3.2a2
MPICH Release date: unreleased development copy
MPICH Device:       ch3:nemesis
MPICH configure:    CC=icc CXX=icpc FC=ifort F77=ifort --enable-fortran --enable-threads=runtime --enable-g=all --with-pm=hydra --prefix=/opt/mpich/dev/intel/debug --enable-wrapper-rpath --enable-static --enable-shared --enable-nemesis-dbg-localoddeven
MPICH CC:   icc    -g -O2
MPICH CXX:  icpc   -g -O2
MPICH F77:  ifort   -g -O2
MPICH FC:   ifort   -g -O2
```

I see the same error with Intel MPI 5.0.2.044, so if it is an MPI bug, it's persisted in MPICH for a while, which is unlikely for something like MPI_Irecv.

**Comment by justusc** [comment]
I was able to replicate the failure on my computer. I used Apple clang-600.0.56 with Accelerate and TBB.

I also checked it with revision 33539885b538bfa3b6875e8f9d98b9435673a1ac to make sure my recent changes in world did not affect the test. The tests results with this revision were unchanged.

**Comment by naromero77** [comment]
The conclusion was that this is an abuse of the TBB program model?

**Comment by naromero77** [comment]
If that is the case, I propose two ideas to close this issue:
1. Fix the actual test
OR
2. Have the test return 0 stating that it only works for the non-TBB version of MADNESS.

**Comment by jeffhammond** [comment]
I don't see how this is related to the use of TBB directly.  I think it's a bug in the code that calls MPI that happens to be a side effect of using TBB.  This should make it easier to diagnose.

This bug should not be closed until it's resolved.  Disabling the test is not a solution.
