### ISSUE TITLE
too noisy gga - fxc, maybe we need something better than rhotol sigmatol params

### ISSUE THREAD

**Issue by alvarovm** [m-a-d-n-e-s-s/madness#117]
I have been trying to compute kernels for GGA xc with libxc and libMADxc, 
I added a test case src/examples/hefxc.cc to plot this function.

the functions fxc I computed are very noisy (see https://www.dropbox.com/s/2dn32s7q5o5mbg6/fxc.png?dl=0 ), when I try to recover potentials multiplying vxc=fxc*rho the potentials have the correct shape close to the nucleus then they have bumps at medium range distances from the origin (see https://www.dropbox.com/s/x36dcevzbe76akq/vxcfromfxc.png?dl=0 )

I wonder if you have any suggestion that I could try to solve this....

**Comment by robertjharrison** [comment]
Alvaro,

    I will have to play to understand the origin of the noise.  The
experiments with the GGA potentials suggests that each one has a different
sensitivity to either/both rho/sigmatol.

   Which GGA are the plots for?

    Why should Vxc = fxc * rho?   I thought V=dE/drho and that f=dV/drho in
a functional sense for the derivatives.

    However, it is indeed fxc*rho that should be smooth.  I.e.,
appropriately bounded noise in fxc is OK if it is where rho is very small.

    Robert

On Wed, Feb 25, 2015 at 2:22 AM, Alvaro Vazquez-Mayagoitia <
notifications@github.com> wrote:

> I have been trying to compute kernels for GGA xc with libxc and libMADxc,
> I added a test case src/examples/hefxc.cc to plot this function.
>
> the functions fxc I computed are very noisy (see
> https://www.dropbox.com/s/2dn32s7q5o5mbg6/fxc.png?dl=0 ), when I try to
> recover potentials multiplying vxc=fxc*rho the potentials have the correct
> shape close to the nucleus then they have bumps at medium range distances
> from the origin (see
> https://www.dropbox.com/s/x36dcevzbe76akq/vxcfromfxc.png?dl=0 )
>
> I wonder if you have any suggestion that I could try to solve this....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/117>.
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by v4m4** [comment]
Hi Robert,
I have played with different values of rhomin, sigmamin, rhotol & sigmatol. and not clue how to not to penalize too much or too low

In the example in hefxc, and in the plots I showed is XC_PBE_X 1.
XC_B88_X also is ugly

** I forgot to mention that fxc for GGA has multiple terms. I am plotting only the term fxc=d^2E/drho^2
For LDA this works very decently

**Comment by robertjharrison** [comment]
#recommended combinations for libxc and GGAs
  #xc GGA_C_LYP 1.0 GGA_X_B88 1.0  RHOTOL 1e-7 RHOMIN 0.0 SIGTOL 0.0 SIGMIN
0.0
  #xc GGA_X_PBE .75 GGA_C_PBE 1. HF_X .25 RHOTOL 0.0 RHOMIN 0.0 SIGTOL 1e-8
SIGMIN 1e-8
  #xc GGA_XC_HCTH_407 RHOTOL 0.0 RHOMIN 0.0 SIGTOL 100.0 SIGMIN 100.0 !!!
PROBABLY BROKEN in LIBXC?
  #xc GGA_X_PW91 1.0 GGA_C_PW91 1.0 RHOTOL 0.0 RHOMIN 0.0 SIGTOL 1e-10
SIGMIN 1e-10
  #xc LDA RHOTOL1e-7 RHOMIN 0.0



On Wed, Feb 25, 2015 at 10:36 AM, Alvaro Vazquez-Mayagoitia <
notifications@github.com> wrote:

> Hi Robert,
> I have played with different values of rhomin, sigmamin, rhotol &
> sigmatol. and not clue how to not to penalize too much or too low
>
> In the example in hefxc, and in the plots I showed is XC_PBE_X 1.
> XC_B88_X also is ugly
>
> ** I forgot to mention that fxc for GGA has multiple terms. I am plotting
> only the term fxc=d^2E/drho^2
> For LDA this works very decently
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/117#issuecomment-75981848>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by v4m4** [comment]
Hi Robert, all
some of the middle range errors seems to be canceled when they are multiplied by very small values of rho...
please have a look to the following plots from hefxc.cc : (red line is the "correct" vxc)

 GGA_X_PBE 1. RHOTOL 0.0 RHOMIN 0.0 SIGTOL 1e-8 SIGMIN 1e-8
https://www.dropbox.com/s/v6mfju7kk2qxro8/fxc-fromvxc-w-robertsugg.png?dl=0
GGA_X_PBE 1. GGA_C_PBE 1.  RHOTOL 0.0 RHOMIN 0.0 SIGTOL 1e-8 SIGMIN 1e-8
https://www.dropbox.com/s/ni7tejgow79n5cy/vxc-fromfxc-pbe.png?dl=0
GGA_C_LYP 1.0 GGA_X_B88 1.0 RHOTOL 1e-7 RHOMIN 0.0 SIGTOL 0.0 SIGMIN 0.0
https://www.dropbox.com/s/mizq4ob3xzxcxfq/vxc-fromfxc-blyp.png?dl=0

looks like the GGA_C terms are more sensible to the cutoff parameters.

I am unsure if I am building correctly the fxc.. I am following the eq. in Mol Phys of T. Yanai, I will investigate more of this

Alvaro

**Comment by robertjharrison** [comment]
Alvaro ... Laura's fix seems to be working very well ... please merge and see if it also works for fxc

**Comment by robertjharrison** [comment]
Fixed by Florian's technique.
