### ISSUE TITLE
x86 macro for tensor asm on phi

### ISSUE THREAD

**Issue by calewis** [m-a-d-n-e-s-s/madness#123]
If compiling for phi the build system picks up the fact that phi is an x86 arch, but the asm code that the x86 macro enables in the tensor library has instructions that are not valid on the phi cards.

**Comment by jeffhammond** [comment]
There are more precise macros than x86 for SSE. I can look them up if
google isn't helpful enough.

On Thursday, May 21, 2015, Drew Lewis <notifications@github.com> wrote:

> If compiling for phi the build system picks up the fact that phi is an x86
> arch, but the asm code that the x86 macro enables in the tensor library has
> instructions that are not valid on the phi cards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/123>.
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by wsttiger** [comment]
I used the -DDISABLE_SSE3 option, and this seemed to work.

**Comment by jeffhammond** [comment]
http://stackoverflow.com/a/28939692/2189128 has everything we need.  To be completely rigorous, we should do configure tests for inline assembly calling the specific instructions we need, but it is possible that those will link but fail at runtime.
