### ISSUE TITLE
Travis-CI

### ISSUE THREAD

**Issue by justusc** [m-a-d-n-e-s-s/madness#130]
The unit test for MRA fails during the testdiff2D due to a timeout. Because there is no output for 10 minutes, I think that there is too computational work for the VM to handle in a reasonable time. I assume that testdiff3D will have a similar problem.

Is there any way to reduce the amount of work for these tests? I see the following variables at the beginning of the file:
```
static const int k = 9 ; // Wavelet order (usually precision + 2)
static const double thresh = 1.e-7 ; // Precision
static const int init_lev = 2;
static int test_axis = 0;
static const double Length = 2.;
```
Would adjusting these have an effect? If so, what would be an appropriate value?

**Comment by robertjharrison** [comment]
These tests are very fast.   Something else is likely wrong.

**Comment by justusc** [comment]
I am running the test on my laptop with MAD_NUM_THREADS=2, the number of threads used with Travis-CI, and testdiff2D has been running for over 36 minutes. If something is wrong, it is not due to the VM.

Perhaps if the number of available threads where larger it would run faster, but with only two available threads it is much too slow.

**Comment by robertjharrison** [comment]
This is on my laptop

rjh@rjhx240:~/Devel/madness/src/madness/mra$ time ./testdiff2D.mpi
MADNESS runtime initialized with 3 threads in the pool and affinity -1 -1 -1
Error in dudx1: 1.32979e-14 PASSED
Error in dudx2: 1.75669e-14 PASSED
Error in dudx3: 1.27546e-14 PASSED
Error in dudx4: 1.22192e-14 PASSED
Error in dudy1: 1.51116e-14 PASSED
Error in dudy2: 2.38329e-14 PASSED
Error in dudy3: 1.49642e-14 PASSED
Error in dudy4: 1.31217e-14 PASSED

real 0m0.202s
user 0m0.195s
sys 0m0.016s



On Sun, May 24, 2015 at 11:57 AM, Justus Calvin <notifications@github.com>
wrote:

> I am running the test on my laptop with MAD_NUM_THREADS=2, the number of
> threads used with Travis-CI, and testdiff2D has been running for over 36
> minutes. If something is wrong, it is not due to the VM.
>
> Perhaps if the number of available threads where larger it would run
> faster, but with only two available threads it is much too slow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/130#issuecomment-105028846>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by robertjharrison** [comment]
I am getting random hangs in testdiff3D ... wonder what changed.

On Sun, May 24, 2015 at 1:37 PM, Robert Harrison <rjharrison@gmail.com>
wrote:

> This is on my laptop
>
> rjh@rjhx240:~/Devel/madness/src/madness/mra$ time ./testdiff2D.mpi
> MADNESS runtime initialized with 3 threads in the pool and affinity -1 -1
> -1
> Error in dudx1: 1.32979e-14 PASSED
> Error in dudx2: 1.75669e-14 PASSED
> Error in dudx3: 1.27546e-14 PASSED
> Error in dudx4: 1.22192e-14 PASSED
> Error in dudy1: 1.51116e-14 PASSED
> Error in dudy2: 2.38329e-14 PASSED
> Error in dudy3: 1.49642e-14 PASSED
> Error in dudy4: 1.31217e-14 PASSED
>
> real 0m0.202s
> user 0m0.195s
> sys 0m0.016s
>
>
>
> On Sun, May 24, 2015 at 11:57 AM, Justus Calvin <notifications@github.com>
> wrote:
>
>> I am running the test on my laptop with MAD_NUM_THREADS=2, the number of
>> threads used with Travis-CI, and testdiff2D has been running for over 36
>> minutes. If something is wrong, it is not due to the VM.
>>
>> Perhaps if the number of available threads where larger it would run
>> faster, but with only two available threads it is much too slow.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/m-a-d-n-e-s-s/madness/issues/130#issuecomment-105028846>
>> .
>>
>
>
>
> --
> Robert J. Harrison
> tel:  865-272-9262
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by justusc** [comment]
That is very strange. I let the test continue to run and it is over 3 hours now. I wonder what the difference is between our setups other than OS.

**Comment by robertjharrison** [comment]
I think something is broken ... it was working (as in we had a problem that
I thought was fixed and it was heavily tested at that point in time).


On Sun, May 24, 2015 at 1:46 PM, Justus Calvin <notifications@github.com>
wrote:

> That is very strange. I let the test continue to run and it is over 3
> hours now. I wonder what the difference is between our setups other than
> OS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/130#issuecomment-105041755>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by robertjharrison** [comment]
If I run testdiff3D with POOL_NTHREAD=1 (TBB and just one process) then it
hangs reproducibly in the same place.

Also, why is GenTensor appearing everywhere?   I thought that was only
being used in the many body code?


On Sun, May 24, 2015 at 1:49 PM, Robert Harrison <rjharrison@gmail.com>
wrote:

> I think something is broken ... it was working (as in we had a problem
> that I thought was fixed and it was heavily tested at that point in time).
>
>
> On Sun, May 24, 2015 at 1:46 PM, Justus Calvin <notifications@github.com>
> wrote:
>
>> That is very strange. I let the test continue to run and it is over 3
>> hours now. I wonder what the difference is between our setups other than
>> OS.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/m-a-d-n-e-s-s/madness/issues/130#issuecomment-105041755>
>> .
>>
>
>
>
> --
> Robert J. Harrison
> tel:  865-272-9262
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by justusc** [comment]
You used 3 threads on your laptop. What happens if you use 2 threads?

**Comment by robertjharrison** [comment]
1 and 2 always hang in the same place

3 hangs at random locations

On Sun, May 24, 2015 at 2:11 PM, Justus Calvin <notifications@github.com>
wrote:

> You used 3 threads on your laptop. What happens if you use 2 threads?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/130#issuecomment-105045552>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by fbischoff** [comment]
If --enable-seprep is disabled upon configuration, GenTensor is just an alias for Tensor. See tensor/gentensor.h:159.

**Comment by justusc** [comment]
I tried increasing the number of threads, but this only allowed a little more progress before a deadlock occurred. So I change the number of threads back to two and removed the tests from the list of unit tests per @robertjharrison recommendation.
