### ISSUE TITLE
SVN revision, git commit labels?

### ISSUE THREAD

**Issue by mgr522** [m-a-d-n-e-s-s/madness#131]
There's a flag in src/examples/Makefile.am called SVNREV that allows example codes to use the SVN revision number.

Seeing as we're no longer using SVN, and there is a similar "GITREV", do we still need/want this variable? ... Only two examples (helium_exact and mp2) are using it anyway.

On a deeper note, should we move the GITREV variable higher up the tree and introduce a madness function that specifies the git commit label? Any application/code that wants it would then have it (not just those in the examples directory...)

**Comment by justusc** [comment]
I would say yes, switch to GITREV.

**Comment by mgr522** [comment]
SVNREV has been deleted. A separate function for the git commit string was also introduced.
