### ISSUE TITLE
madness::Vector

### ISSUE THREAD

**Issue by mgr522** [m-a-d-n-e-s-s/madness#132]
madness::Vector (in world/array.h) encapsulates a std::array and adds some mathematical and I/O functionality. Instead of wrapping a std::array (thus necessitating many wrapper functions), could madness::Vector inherit from std::array? We would then only have to implement the additional functions.

Maybe I'm missing something?

**Comment by justusc** [comment]
It is probably ok to make such a change, but I am not sure what the general guidelines are for this situation.
