### ISSUE TITLE
MRA tests exceed Travis-CI time limit

### ISSUE THREAD

**Issue by justusc** [m-a-d-n-e-s-s/madness#134]
Currently all enabled tests in the MRA directory seem to run correctly, but they exceed the 50 minute time limit for Travis-CI. We may be able to improved the runtime by switching over to Travis-CI docker solution since we get more memory (4 GB, up from 3GB) and more cores (2, up from 1.5). But we need to wait for some of our package dependencies to be white listed before we can implement this solution (see issues travis-ci/travis-ci#3846, travis-ci/travis-ci#3954, travis-ci/travis-ci#3955, travis-ci/travis-ci#3956, and travis-ci/travis-ci#3957). Even with the improved performance of the new test platform, I am not optimistic that this will be enough.

**Comment by naromero77** [comment]
What is Travis-CI docker solution?


On Mon, May 25, 2015 at 8:30 AM, Justus Calvin <notifications@github.com>
wrote:

> Currently all enabled tests in the MRA directory seem to run correctly,
> but they exceed the 50 minute time limit for Travis-CI. We may be able to
> improved the runtime by switching over to Travis-CI docker solution since
> we get more memory (4 GB, up from 3GB) and more cores (2, up from 1.5). But
> we need to wait for some of our package dependencies to be white listed
> before we can implement this solution (see issues travis-ci/travis-ci#3846
> <https://github.com/travis-ci/travis-ci/issues/3846>,
> travis-ci/travis-ci#3954
> <https://github.com/travis-ci/travis-ci/issues/3954>,
> travis-ci/travis-ci#3955
> <https://github.com/travis-ci/travis-ci/issues/3955>,
> travis-ci/travis-ci#3956
> <https://github.com/travis-ci/travis-ci/issues/3956>, and
> travis-ci/travis-ci#3957
> <https://github.com/travis-ci/travis-ci/issues/3957>). Even with the
> improved performance of the new test platform, I am not optimistic that
> this will be enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/134>.
>



-- 
Nichols A. Romero, Ph.D.

**Comment by justusc** [comment]
It is a thin VM.

http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
