### ISSUE TITLE
many failing tests

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#135]
Hi all,

my nightly test suite failed for many tests:

$ grep FAIL test.log 
FAIL: test_future.mpi
FAIL: test_future3.mpi
FAIL: test_world.mpi
FAIL: testbsh.mpi
FAIL: testproj.mpi
FAIL: testpdiff.mpi
FAIL: testper.mpi
FAIL: testdiff1Db.mpi
FAIL: testgconv.mpi
FAIL: testopdir.mpi
FAIL: testsuite.mpi
FAIL: testinnerext.mpi
FAIL: testgaxpyext.mpi
FAIL: testvmra.mpi

The tested version was 6254b8dfb579d8a9a59b127b5d913ba31a1d908a, but the error might as well have appeared earlier. Last working version was 4e419c123d27eca8f9abe72413e507de673f1afb. The traceback in test_future was:

Program received signal SIGSEGV, Segmentation fault.
0x000000000040685e in void madness::ThreadPool::await<madness::FutureImpl<std::string>::get()::{lambda()#1}>(madness::FutureImpl<std::string>::get()::{lambda()#1} const&, bool) [clone .constprop.138] ()
(gdb) up
#1  0x00000000004092d7 in madness::Future<std::string>::get() ()
(gdb) 
#2  0x0000000000405e7c in main ()

Machine is linux x86_64, configure options were
'--enable-gentensor' '--with-google-perf=/apps/devel/gperftools' '--with-tbb' '--with-tbb-lib=/opt/intel/XE2013.SP1/tbb//lib/intel64/gcc4.4/' '--with-libxc=/apps/devel/libxc' '--with-google-test' 'CXXFLAGS=-std=c++11' 'CC=/usr/bin/gcc-4.7 -m64' 'MPICC=/apps/devel/mvapich2/bin/mpicc' 'MPICXX=/apps/devel/mvapich2/bin/mpicxx' 'CXX=/usr/bin/g++-4.7 -m64' 'F77=/usr/bin/gfortran-4.7 -m64' 'MKLROOT=/opt/intel/XE2013.SP1/composer_xe_2013_sp1.1.106/mkl'

Florian

**Comment by justusc** [comment]
Unfortunately, I do not see the same failures. Everything passed on my laptop except testsuite.mpi in MRA and everything that ran in the Travis-CI tests passed.

Can you give some details about your system? OS, compiler and version, config, and relevant software stack and versions. Also, do you have full output?

Justus


The output on my laptop is:

$ make -j4 check
PASS: test_ar.mpi
PASS: test_hello.mpi
PASS: test_hashdc.mpi
PASS: test_prof.mpi
PASS: test_future.mpi
PASS: test_future2.mpi
PASS: test_future3.mpi
PASS: test_dc.mpi
PASS: test_world.mpi
PASS: test_worldprofile.mpi
PASS: test_binsorter.mpi
PASS: test_vector.mpi
PASS: test_worldptr.mpi
PASS: test_worldref.mpi
PASS: test_queue.mpi
PASS: test_atomicint.mpi
PASS: test_hashthreaded.mpi
============================================================================
Testsuite summary for MADNESS 0.10
============================================================================
# TOTAL: 17
# PASS:  17
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

PASS: interp3
============================================================================
Testsuite summary for MADNESS 0.10
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

PASS: test_mtxmq.seq
PASS: test_scott.seq
PASS: test_linalg.seq
PASS: test_solvers.seq
PASS: test_elemental.mpi
PASS: testseprep.seq
PASS: test_distributed_matrix.mpi
PASS: test
PASS: test_gentensor
PASS: jimkernel.seq
PASS: oldtest.seq
PASS: test_Zmtxmq.seq
============================================================================
Testsuite summary for MADNESS 0.10
============================================================================
# TOTAL: 12
# PASS:  12
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

PASS: testper.mpi
PASS: testpdiff.mpi
PASS: testdiff1Db.mpi
PASS: testgconv.mpi
PASS: testbsh.mpi
PASS: testinnerext.mpi
PASS: testgaxpyext.mpi
PASS: testopdir.mpi
PASS: testproj.mpi
FAIL: testsuite.mpi
PASS: testvmra.mpi
============================================================================
Testsuite summary for MADNESS 0.10
============================================================================
# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/madness/mra/test-suite.log
Please report to https://github.com/m-a-d-n-e-s-s/madness
============================================================================

**Comment by fbischoff** [comment]
It also works on my laptop, but not on my linux machine. System details are in the original mail: linux, gcc-4.7, mvapich2, traceback, config options. Full output is:

[13:38] test_future.mpi 
MADNESS runtime initialized with 7 threads in the pool and affinity -1 -1 -1
[hawaii:mpi_rank_0][error_sighandler] Caught error: Segmentation fault (signal 11)
Segmentation fault

Florian

**Comment by fbischoff** [comment]
The segfault came with commit f8842f7dc58fc8ba49e0726548d31d74e8efbab4. It occurs with and without optimization. Maybe an issue with gcc-4.7.2 ?

**Comment by justusc** [comment]
Yes, it is likely an issue with GCC 4.7.2. I think we can work around the limitation and still keep the lambda functions from that commit.

**Comment by justusc** [comment]
I pushed a possible fix to the issue.

**Comment by fbischoff** [comment]
Thanks, this works
