### ISSUE TITLE
Memory leak in DQueue::grow()?

### ISSUE THREAD

**Issue by justusc** [m-a-d-n-e-s-s/madness#138]
I am 99% certain I found a memory leak in DQueue::grow(). Since this is in a performance critical section, I want to be sure that there is nothing strange going on here, like purposefully leaking the memory, etc. I do not see any calls to delete in the file, other than in the destructor.

The relevant code is given below (see the comment at the end).

```c++
void grow() {
    // ASSUME WE ALREADY HAVE THE MUTEX WHEN IN HERE
    ++(stats.ngrow);
    if (sz != n) MADNESS_EXCEPTION("assertion failure in dqueue::grow", static_cast<int>(sz));
    size_t oldsz = sz;
    if (sz < 32768)
        sz = 65536;
    else if (sz <= 1048576)
        sz *= 2;
    else
        sz += 1048576;
    volatile T* volatile nbuf = new T[sz];
    int lo = sz/2 - oldsz/2;
    for (int i=_front; i<int(oldsz); ++i,++lo) {
        nbuf[lo] = buf[i];
    }
    if (_front > 0) {
        for (int i=0; i<=_back; ++i,++lo) {
            nbuf[lo] = buf[i];
        }
    }
    _front = sz/2 - oldsz/2;
    _back = _front + n - 1;
    //<<<<<<<<<<<<<<<<<<<<<< there should be a "delete [] buf;" here
    buf = nbuf;
    //sanity_check();
}
```

**Comment by robertjharrison** [comment]
I agree.  But unless there are uses I am not aware of the leak is small
since there is only one instance of the task q per process and typically we
only have a few 10k as the max q Len.

Grow is not performance critical.  Dont even know if it is ever called ...
Depends on the size the queue is constructed with

**Comment by justusc** [comment]
Ok, I thought that might be the case but I was not sure. I'll go ahead and push the fix.
