### ISSUE TITLE
Release tarballs should not require autotools

### ISSUE THREAD

**Issue by mbanck** [m-a-d-n-e-s-s/madness#140]
The tag-based tarballs for 0.10 from github are just a tarball of the git repository.

However, I think the project should provide end-user tarballs from 'make dist' or 'make distcheck' or so, so that one can run the usual './configure && make && make install' without having to install autoconf or automake.

Somewhat related, a simple 'autoreconf -fi; ./configure; make dist/distcheck' fails for me like that:

```
make[3]: *** No rule to make target '../apps/DFcode/xcfunctional_madxc.cc', needed by 'distdir'.  Stop.
```

**Comment by justusc** [comment]
You need to run the autogen.sh script (found in the root source directory), to properly generate the configure script. If that does not work, you may need to delete the build directory and start over again. If that still does not work, please let us know.

You may want to consider installing libxc, as libmadxc may be going away in the future.

The tar ball available for download was automatically generated by the GitHub. Generating a distribution tar ball is on my list of things to do.

**Comment by mbanck** [comment]
Right, I realized there's an autogen.sh immediately after I submitted the issue, my main point is that it shouldn't be necessary to do that for release tarballs. Maybe I should have worded the issue more like "release tarballs are missing" or so.

**Comment by justusc** [comment]
I tagged a new release and uploaded new source files.
