### ISSUE TITLE
Shared library support

### ISSUE THREAD

**Issue by mbanck** [m-a-d-n-e-s-s/madness#141]
It seems there is no shared library support. Is this becuase madness is currently not supposed to be in run in production/beta software, or is this just a bug/oversight?

**Comment by justusc** [comment]
MADNESS target applications run on large supper computers, which typically require static libraries. However, most of our development work is done on work stations and laptops, and static libraries work just fine for this purpose. Dynamic library support was never added because there has not been a pressing need for that feature.

However, if you have a target application where dynamic libraries are desirable/required we may be able to add that feature.

**Comment by mbanck** [comment]
Dynamic libraries are desirable/required for any Linux distribution packaging madness, at least once more than 1 or 2 packages would be using it.

I've mostly been looking at madness cause it used by TiledArray which again is used by MPQC3 - maybe those all pull in each other's code via external/ (like madness does for elemental), but that is no workable solution for Linux distributions.

That said, just shipping a development package (including the static libraries and the header files) is ok for the moment, but I think shipping a shared library (and maintaining a library interface) would be useful once the API is stable.

**Comment by mbanck** [comment]
The other possible reason for shared libraries are the rather steep disk space requirements for building madness - it took roughly 10 GB here, mostly because all the test programs include a copy of all the libraries.

**Comment by justusc** [comment]
I will look into enabling it.

**Comment by mbanck** [comment]
Note that shared libraries come with the burden of maintaining library versioning (once you change or remove functions from the API, you need to rev the library version).

The madness maintainers (so you, I guess :) ) would be best to know if/when the madness API has stabilized, and at that point shipping shared libraries would be desirable.

**Comment by jeffhammond** [comment]
Or we just assume user builds self-consistently. I don't know that it's a
worthwhile trade off to rigorously maintain x.y.z versioning of shared
objects.

On Sunday, July 5, 2015, Michael Banck <notifications@github.com> wrote:

> Note that shared libraries come with the burden of maintaining library
> versioning (once you change or remove functions from the API, you need to
> rev the library version).
>
> The madness maintainers (so you, I guess :) ) would be best to know
> if/when the madness API has stabilized, and at that point shipping shared
> libraries would be desirable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/141#issuecomment-118613948>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by justusc** [comment]
Shared libraries appear to be working (CI unit tests are passing). I will add make a new tar ball and update the tag for the v0.10 release some time in the near future.
