### ISSUE TITLE
make distclean on clean configure not working

### ISSUE THREAD

**Issue by mbanck** [m-a-d-n-e-s-s/madness#142]
Running ./configure && make distclean leads to an dependency error:

```
make[2]: Entering directory '/home/mbanck/debian/debichem/madness-0.10/src/examples'
Makefile:833: ../apps/chem/.deps/TDA.Po: No such file or directory
Makefile:834: ../apps/chem/.deps/TDA_XC.Po: No such file or directory
Makefile:835: ../apps/chem/.deps/xcfunctional_ldaonly.Po: No such file or directory
Makefile:836: ../apps/chem/.deps/xcfunctional_libxc.Po: No such file or directory
make[2]: *** No rule to make target '../apps/chem/.deps/xcfunctional_libxc.Po'.  Stop.
make[2]: Leaving directory '/home/mbanck/debian/debichem/madness-0.10/src/examples'
Makefile:425: recipe for target 'distclean-recursive' failed
make[1]: *** [distclean-recursive] Error 1
make[1]: Leaving directory '/home/mbanck/debian/debichem/madness-0.10/src'
Makefile:401: recipe for target 'distclean-recursive' failed
make: *** [distclean-recursive] Error 1
```

**Comment by justusc** [comment]
This is probably caused by the same issue as I described in #140. Again, please let me know if the issue persists.

**Comment by mbanck** [comment]
No, this is not related - if I hadn't run autogen.sh (or autoreconf, which does the same), then there wouldn't be a ./configure to run.

I checked with a fresh git clone and running "./autogen.sh; ./configure; make distclean" I still get the error. 

I believe this is due to the inter-directory dependencies of one the examples to apps/chem, but I have not analyzed this in detail or have a solution for it right now.

**Comment by mbanck** [comment]
If I remove the "[...]SOURCES += ../apps/chem/[...]" lines from src/examples/Makefile.am (see below for a diff), I can run make distclean fine.

libMADchem.a (which includes the ../apps/chem object files) gets linked in anyway as $(LIBCHEM), so this should not be a big problem. I am less clear on the MADNESS_HAS_MADXC stuff, cause there is no ../apps/DFcode directory in the current code, is this legacy or for unpublished/add-on code?

My diff is:

```
diff --git a/src/examples/Makefile.am b/src/examples/Makefile.am
index 2b66cea..5ea1b55 100644
--- a/src/examples/Makefile.am
+++ b/src/examples/Makefile.am
@@ -44,16 +44,6 @@ hedft_SOURCES = hedft.cc
 h2dft_SOURCES = h2dft.cc
 if MADNESS_HAS_LIBXC
 hefxc_SOURCES = hefxc.cc  
-hefxc_SOURCES += ../apps/chem/xcfunctional_libxc.cc
-hedft_SOURCES += ../apps/chem/xcfunctional_libxc.cc
-h2dft_SOURCES += ../apps/chem/xcfunctional_libxc.cc
-endif
-if MADNESS_HAS_MADXC
-hedft_SOURCES += ../apps/DFcode/xcfunctional_madxc.cc 
-h2dft_SOURCES += ../apps/DFcode/xcfunctional_madxc.cc 
-else
-hedft_SOURCES += ../apps/chem/xcfunctional_ldaonly.cc 
-h2dft_SOURCES += ../apps/chem/xcfunctional_ldaonly.cc 
 endif
 
 sininteg_SOURCES = sininteg.cc
```
