### ISSUE TITLE
wrong cmake config file directory

### ISSUE THREAD

**Issue by mbanck** [m-a-d-n-e-s-s/madness#151]
The automake file config/Makefile.am installs madness-config.cmake as follows:

```
cmakeconfigdir = $(libdir)/CMake/Madness
```

However, CMake's find_package() function seems to be only checking in lower-case $(libdir)/cmake/Madness on my (Linux) system. This seems to be the relevant line in cmake:

http://www.cmake.org/gitweb?p=cmake.git;a=blob;f=Source/cmFindPackageCommand.cxx;h=68a6558fe18a8eec2c734f5ee630923708294730;hb=HEAD#l2116

```
//  PREFIX/(lib/ARCH|lib|share)/cmake/(Foo|foo|FOO).*/
{
cmFindPackageFileList lister(this);
lister
  / cmFileListGeneratorFixed(prefix)
  / cmFileListGeneratorEnumerate(common)
  / cmFileListGeneratorFixed("cmake")
  / cmFileListGeneratorProject(this->Names);
if(lister.Search())
  {
  return true;
  }
}
```

Note the lower-case cmake. Indeed, if I symlink cmake -> CMake or patch Madness' cmake config file accordingly, Madness gets properly found.

The upstream documentation seems to support that lib/CMake is not a proper path, see http://www.cmake.org/cmake/help/git-master/command/find_package.html#command:find_package and especially the list of directories after "CMake constructs a set of possible installation prefixes for the package":

```
<prefix>/                                               (W)
<prefix>/(cmake|CMake)/                                 (W)
<prefix>/<name>*/                                       (W)
<prefix>/<name>*/(cmake|CMake)/                         (W)
<prefix>/(lib/<arch>|lib|share)/cmake/<name>*/          (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/                (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (U)
```

**Comment by mbanck** [comment]
So I suggest the following patch:

```
+++ ./config/Makefile.am        2015-08-01 18:46:01.691410474 +0200
@@ -3,5 +3,5 @@
 pkgconfig_DATA = MADNESS.pc

 # MADNESS CMake configuration file
-cmakeconfigdir = $(libdir)/CMake/Madness
-cmakeconfig_DATA = madness-config.cmake
\ No newline at end of file
+cmakeconfigdir = $(libdir)/cmake/Madness
+cmakeconfig_DATA = madness-config.cmake
```

**Comment by justusc** [comment]
Fix is incoming.
