### ISSUE TITLE
spin-polarized DFT broken

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#153]
Spin-polarized DFT is broken, even for LDA. whereas Hartree-Fock works. Haven't figured out quite yet what's the problem, but at least this line looks strange to me: xcfunctional_libxc:537

**Comment by justusc** [comment]
Broken how?

**Comment by fbischoff** [comment]
The closed-shell water molecule (any closed-shell molecule) should give the same energy if run spin-polarized or spin-unpolarized.

**Comment by robertjharrison** [comment]
In the build I have (from about 1 month old source) it is working (for
water) and even converges at exactly the same rate as the closed shell.
The closed shell runs in 56s and the open shell in 116 ... linear scaling
in the number of orbitals.

I cannot figure out how to get the hash for the version I am building



On Mon, Aug 10, 2015 at 8:24 AM, fbischoff <notifications@github.com> wrote:

> The closed-shell water molecule (any closed-shell molecule) should give
> the same energy if run spin-polarized or spin-unpolarized.
>
>
> On Aug 10, 2015, at 2:22 PM, Justus Calvin <notifications@github.com>
> wrote:
>
> > Broken how?
> >
> > �
>
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/153#issuecomment-129426180>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by mgr522** [comment]
You can try the git_commit function in madness/world/info.h to get the hash.

**Comment by jeffhammond** [comment]
Or use this:
`
git info | grep commit
commit ce73725af8e1b362bc04690a64086bfa963f66e8
`

**Comment by justusc** [comment]
git rev-parse HEAD

**Comment by robertjharrison** [comment]
so this version appears to be working (on my laptop, YMMVOAM)

e27eeaaa7519277995a4d8efea11ef4c5ee2d009


On Tue, Aug 11, 2015 at 8:51 PM, Justus Calvin <notifications@github.com>
wrote:

> git rev-parse HEAD





-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by fbischoff** [comment]
Ok, maybe it's actually my fault then.. I will have a look into it when I'm back from vacation in two weeks

**Comment by fbischoff** [comment]
fixed the bug, opened a new issue for Function inplace addition

**Comment by robertjharrison** [comment]
good catch!

Do you have the test case that exposed this?  When I ran LSDA water I got
agreement with LDA.

On Fri, Aug 28, 2015 at 4:10 AM, fbischoff <notifications@github.com> wrote:

> fixed the bug, opened a new issue for Function inplace addition
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/153#issuecomment-135667518>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262
