### ISSUE TITLE
Function inplace addition

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#155]
Just fixed the UKS bug, which came from unexpected behavior of the inplace addition of two functions. The following blocks should do the same:

func1 = func0;
func1 = func1 + func2; 

func1 = func0;
func1 += func2; 

but instead the first block reassigns func1 (including a deep copy), and the second block does not. Thus in the first case func0 is changed, but not in the second. I think they should behave consistently.

**Comment by robertjharrison** [comment]
The codes are different and do different things.  I don't think the new
behavior you describe is correct.

Function assignment is shallow, just like a python container or a madness
tensor ... so by writing in the first piece of code

func1 = func0

we are not copying any data

func1 = func1 + func2

should have added func1 and func2 without modifying them (except perhaps
compression) and then assigned the new function to the variable func1.  At
this point func1 and func0 should refer to different functions.   Was this
not happening?

In the second code, we again start by creating an alias, and then do the
inplace modification.  Both func1 and func0 refer to the same function so
"both" are modified.  This is as desired and is exactly like a python
container

>>> a = []
>>> b = a
>>> b.append(1)
>>> a
[1]

I think the old behavior was correct, and the bug in the code was not
taking a deecopy when one was wanted.





On Fri, Aug 28, 2015 at 4:17 AM, fbischoff <notifications@github.com> wrote:

> Just fixed the UKS bug, which came from unexpected behavior of the inplace
> addition of two functions. The following blocks should do the same:
>
> func1 = func0;
> func1 = func1 + func2;
>
> func1 = func0;
> func1 += func2;
>
> but instead the first block reassigns func1 (including a deep copy), and
> the second block does not. Thus in the first case func0 is changed, but not
> in the second. I think they should behave consistently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/155>.
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by fbischoff** [comment]
The original code was like func1 = func1 + func2, which was correct, and the bug that I introduced had the inplace addition. Just tried to do some code-cleaning without paying enough attention. I was simply wondering if 

func1=func1+func2 

and 

func1+=func2

should always behave identically.

**Comment by robertjharrison** [comment]
No, the two things are different.

On Fri, Aug 28, 2015 at 7:45 AM, fbischoff <notifications@github.com> wrote:

> The original code was like func1 = func1 + func2, which was correct, and
> the bug that I introduced had the inplace addition. Just tried to do some
> code-cleaning without paying enough attention. I was simply wondering if
>
> func1=func1+func2
>
> and
>
> func1+=func2
>
> should always behave identically.
>
>
>
> On Aug 28, 2015, at 12:53 PM, robertjharrison <notifications@github.com>
> wrote:
>
> > The codes are different and do different things. I don't think the new
> > behavior you describe is correct.
> >
> > Function assignment is shallow, just like a python container or a madness
> > tensor ... so by writing in the first piece of code
> >
> > func1 = func0
> >
> > we are not copying any data
> >
> > func1 = func1 + func2
> >
> > should have added func1 and func2 without modifying them (except perhaps
> > compression) and then assigned the new function to the variable func1. At
> > this point func1 and func0 should refer to different functions. Was this
> > not happening?
> >
> > In the second code, we again start by creating an alias, and then do the
> > inplace modification. Both func1 and func0 refer to the same function so
> > "both" are modified. This is as desired and is exactly like a python
> > container
> >
> > >>> a = []
> > >>> b = a
> > >>> b.append(1)
> > >>> a
> > [1]
> >
> > I think the old behavior was correct, and the bug in the code was not
> > taking a deecopy when one was wanted.
> >
> >
> >
> >
> >
> > On Fri, Aug 28, 2015 at 4:17 AM, fbischoff <notifications@github.com>
> wrote:
> >
> > > Just fixed the UKS bug, which came from unexpected behavior of the
> inplace
> > > addition of two functions. The following blocks should do the same:
> > >
> > > func1 = func0;
> > > func1 = func1 + func2;
> > >
> > > func1 = func0;
> > > func1 += func2;
> > >
> > > but instead the first block reassigns func1 (including a deep copy),
> and
> > > the second block does not. Thus in the first case func0 is changed,
> but not
> > > in the second. I think they should behave consistently.
> > >
> > > �
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/m-a-d-n-e-s-s/madness/issues/155>.
> > >
> >
> >
> >
> > --
> > Robert J. Harrison
> > tel: 865-272-9262
> > �
>
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/155#issuecomment-135747012>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by jeffhammond** [comment]
I don't want to live in a world where
y+=x
and
y=y+x
are not the same thing.

Fortran is such a world, but only because the latter is a syntax error.
Silent differences between the two are evil.

Jeff

On Friday, August 28, 2015, robertjharrison <notifications@github.com>
wrote:

> No, the two things are different.
>
> On Fri, Aug 28, 2015 at 7:45 AM, fbischoff <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > The original code was like func1 = func1 + func2, which was correct, and
> > the bug that I introduced had the inplace addition. Just tried to do some
> > code-cleaning without paying enough attention. I was simply wondering if
> >
> > func1=func1+func2
> >
> > and
> >
> > func1+=func2
> >
> > should always behave identically.
> >
> >
> >
> > On Aug 28, 2015, at 12:53 PM, robertjharrison <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > The codes are different and do different things. I don't think the new
> > > behavior you describe is correct.
> > >
> > > Function assignment is shallow, just like a python container or a
> madness
> > > tensor ... so by writing in the first piece of code
> > >
> > > func1 = func0
> > >
> > > we are not copying any data
> > >
> > > func1 = func1 + func2
> > >
> > > should have added func1 and func2 without modifying them (except
> perhaps
> > > compression) and then assigned the new function to the variable func1.
> At
> > > this point func1 and func0 should refer to different functions. Was
> this
> > > not happening?
> > >
> > > In the second code, we again start by creating an alias, and then do
> the
> > > inplace modification. Both func1 and func0 refer to the same function
> so
> > > "both" are modified. This is as desired and is exactly like a python
> > > container
> > >
> > > >>> a = []
> > > >>> b = a
> > > >>> b.append(1)
> > > >>> a
> > > [1]
> > >
> > > I think the old behavior was correct, and the bug in the code was not
> > > taking a deecopy when one was wanted.
> > >
> > >
> > >
> > >
> > >
> > > On Fri, Aug 28, 2015 at 4:17 AM, fbischoff <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > >
> > > > Just fixed the UKS bug, which came from unexpected behavior of the
> > inplace
> > > > addition of two functions. The following blocks should do the same:
> > > >
> > > > func1 = func0;
> > > > func1 = func1 + func2;
> > > >
> > > > func1 = func0;
> > > > func1 += func2;
> > > >
> > > > but instead the first block reassigns func1 (including a deep copy),
> > and
> > > > the second block does not. Thus in the first case func0 is changed,
> > but not
> > > > in the second. I think they should behave consistently.
> > > >
> > > > �
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/m-a-d-n-e-s-s/madness/issues/155>.
> > > >
> > >
> > >
> > >
> > > --
> > > Robert J. Harrison
> > > tel: 865-272-9262
> > > �
> >
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/issues/155#issuecomment-135747012
> >
> > .
> >
>
>
>
> --
> Robert J. Harrison
> tel: 865-272-9262
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/155#issuecomment-135749153>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by robertjharrison** [comment]
Clearly they are different regardless of shallow copy or not.

One allocates new memory and the other operates in place.

We are moving away from mutable data but it will be a while until that
happens. When it does += goes away or is at least reinterpreted as not
being literally in place.

Shallow copy is a separate issue.  For now this is how the code works.
When we move to immutable data we will retain it but the side effects will
vanish.

**Comment by fbischoff** [comment]
It's not a bug, it's a feature
