### ISSUE TITLE
moldft lda is not working

### ISSUE THREAD

**Issue by v4m4** [m-a-d-n-e-s-s/madness#159]
moldft DFT calcs without libxc (ie. only lda) is not working

The post-mortem message is this: 
 
A madness exception occurred. Place a break point at madness::exception_break to debug.
MadnessException : msg=MADNESS ASSERTION FAILED: "xcfunctional_ldaonly.cc"(108) : assertion=t.size() == 1 : value=0 : line=108 : function=exc : filename='xcfunctional_ldaonly.cc'

MADNESS: fatal error: MadnessException : msg=MADNESS ASSERTION FAILED: "xcfunctional_ldaonly.cc"(108)caught a MADNESS exception : 
!!MADNESS ERROR: Exception thrown in WorldTaskQueue::fence() with 456 pending task(s)
assertion=t.size() == 1 : value=0 : line=108 : function=exc : filename='xcfunctional_ldaonly.cc'

MADNESS: fatal error: caught a MADNESS exception
MadnessException : msg=MADNESS ASSERTION FAILED: "xcfunctional_ldaonly.cc"(108) : assertion=t.size() == 1 : value=0 : line=108 : function=exc : filename='xcfunctional_ldaonly.cc'

MADNESS: fatal error: MadnessException : msg=MADNESS ASSERTION FAILED: "xcfunctional_ldaonly.cc"(108) : assertion=t.size() == 1 : value=0caught a MADNESS exception : line=108 : function=
exc : filename='xcfunctional_ldaonly.cc'

MADNESS: fatal error: caught a MADNESS exceptionMadnessException : msg=MADNESS ASSERTION FAILED: "xcfunctional_ldaonly.cc"(108) : assertion=t.size() == 1 : value=0 : line=108 : function=exc : filename='xcfunctional_ldaonly.cc'
*** Error in `/home/vama/chem2/m-a-d-n-e-s-s/madness/src/apps/moldft/.libs/lt-moldft
': corrupted double-linked list: 0x
0000000001b7d2c0 ***
MadnessException : msg=MADNESS ASSERTION FAILED: "xcfunctional_ldaonly.cc"(108) : assertion=t.size() == 1 : value=0 : line=108 : function=exc : filename='xcfunctional_ldaonly.cc'

MADNESS: fatal error: caught a MADNESS exception
MADNESS: fatal error: MadnessException : msg=MADNESS ASSERTION FAILED: "xcfunctional_ldaonly.cc"(108) : assertion=t.size() == 1 : value=0 : line=108 : function=exc : filename='xcfunctional_ldaonly.cc'

MADNESS: fatal error: caught a MADNESS exception
caught a MADNESS exception
Aborted (core dumped)

**Comment by fbischoff** [comment]
fixed with commit 4df69b4e0564c0b445a73d6f290be83e3244262b
