### ISSUE TITLE
compilations with gcc-4.9 and  --with-stubmpi hang at finalize()

### ISSUE THREAD

**Issue by alvarovm** [m-a-d-n-e-s-s/madness#161]
I am compiling with this option

BLASLIB="-L/opt/intel/mkl/lib/intel64  -lmkl_gf_lp64  -lmkl_core -lmkl_sequential  -lpthread -lm" \
LAPACKLIB="-L/opt/intel/mkl/lib/intel64  -lmkl_gf_lp64  -lmkl_core -lmkl_sequential  -lpthread -lm" \
CXX=g++ FC=gfortran CC=gcc \
./configure --enable-optimization=no  --enable-optimal=yes \
     -enable-debugging=yes --with-tbb=no  --with-stubmpi

**Comment by naromero77** [comment]
which MPI did you use?

On Tue, Oct 13, 2015 at 11:43 AM, Alvaro Vazquez-Mayagoitia <
notifications@github.com> wrote:

> I am compiling with this option
>
> BLASLIB="-L/opt/intel/mkl/lib/intel64 -lmkl_gf_lp64 -lmkl_core
> -lmkl_sequential -lpthread -lm" \
> LAPACKLIB="-L/opt/intel/mkl/lib/intel64 -lmkl_gf_lp64 -lmkl_core
> -lmkl_sequential -lpthread -lm" \
> CXX=g++ FC=gfortran CC=gcc \
> ./configure --enable-optimization=no --enable-optimal=yes \
> -enable-debugging=yes --with-tbb=no --with-stubmpi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/161>.
>



-- 
Nichols A. Romero, Ph.D.

**Comment by v4m4** [comment]
none

**Comment by naromero77** [comment]
Right, I forget the purpose of stub-mpi.

On Tue, Oct 13, 2015 at 12:23 PM, Alvaro Vazquez-Mayagoitia <
notifications@github.com> wrote:

> none
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/161#issuecomment-147783736>
> .
>



-- 
Nichols A. Romero, Ph.D.

**Comment by jeffhammond** [comment]
Of using stub MPI then trivial to run gdb bt and know exactly where it
hangs.

On Tuesday, October 13, 2015, Nichols A. Romero <notifications@github.com>
wrote:

> Right, I forget the purpose of stub-mpi.
>
> On Tue, Oct 13, 2015 at 12:23 PM, Alvaro Vazquez-Mayagoitia <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > none
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/issues/161#issuecomment-147783736
> >
> > .
> >
>
>
>
> --
> Nichols A. Romero, Ph.D.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/161#issuecomment-147786682>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/
