### ISSUE TITLE
use {c,z}gemm3m if MKL is present

### ISSUE THREAD

**Issue by evaleev** [m-a-d-n-e-s-s/madness#167]
refs: https://github.com/ValeevGroup/tiledarray/issues/56 , https://software.intel.com/en-us/node/468652

**Comment by jeffhammond** [comment]
:+1:

I learned about this from Toru's code.  I think [BLIS](https://github.com/flame/blis) might support the same feature at some point in the future, so there may be an open-source alternative to MKL at some point.

Of course, now that MKL is free as in beer for all, it should be a lot easier to convince people to accept MKL extensions to Netlib.

**Comment by naromero77** [comment]
Cool

On Mon, Dec 14, 2015 at 1:26 PM, Jeff Hammond <notifications@github.com>
wrote:

> [image: :+1:]
>
> I learned about this from Toru's code. I think BLIS
> <https://github.com/flame/blis> might support the same feature at some
> point in the future, so there may be an open-source alternative to MKL at
> some point.
>
> Of course, now that MKL is free as in beer for all, it should be a lot
> easier to convince people to accept MKL extensions to Netlib.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/167#issuecomment-164534014>
> .
>



-- 
Nichols A. Romero, Ph.D.
