### ISSUE TITLE
circular dependencies and encapsulation in mra.h

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#17]
Hi all,

I'm trying to go through the various includes in the code, and there seems to be some circular dependencies that I would like to resolve. My understanding of the current implementation is this:
- mra.h is included in the binaries (examples, moldft, etc)
- the implementation of Function via FunctionImpl is hidden in funcimpl.h and mraimpl.h
- mra.h should not include funcimpl.h and mraimpl.h

However, funcimpl.h and mraimpl.h are included in mra.h (at the top and the bottom), so they are exposed to the outside world. This leads to very long complilation times. When I remove the includes the code doesn't compile, because the FunctionImpl class and its members must be declared when its member functions are called in Function (forward declaration of FunctionImpl alone didn't work). Therefore I must include the FunctionImpl declaration in mra.h. 

I can move the definitions of the FunctionImpl member to mraimpl.h and keep only the declarations in Function. When I do this I have to explicitly instantiate the member functions in mra1.cc thru mra6.cc like:

template Void FunctionImpl<double, 1ul>::reconstruct_op(const Key<1ul>&, const GenTensor<double>& );

I guess an alternative would be to move the Function member functions to an extra definition file (instead of the FunctionImpl member functions in mraimpl.h). FunctionImpl.h could then be included in that definition file without violating the encapsulation.

Now the questions are: 
- is this understanding correct?
- is there another, maybe better way to solve this?

There seem to be a lot of pitfalls, so I would like to know your opinion on this.

Florian

**Comment by naromero77** [comment]
Is this still an open issue?
