### ISSUE TITLE
compile-time warning of test_systolic.cc 

### ISSUE THREAD

**Issue by naromero77** [m-a-d-n-e-s-s/madness#178]
Is this something we should be concerned about?

``` sh
mpicxx -DHAVE_CONFIG_H   -I../../../../madness-git-naromero/src -I../../../src -I../../../../madness-git-naromero/src/apps -I/home/naromero/libxc-2.0.x/include -I/home/naromero/gperftools-2.2.1-GCC4.8.3/include  -DMPICH_SKIP_MPICXX=1 -DOMPI_SKIP_MPICXX=1  -O3 -std=c++11 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -g -Wall -Wno-strict-aliasing -Wno-deprecated -Wno-unused-local-typedefs -MT test_systolic.o -MD -MP -MF .deps/test_systolic.Tpo -c -o test_systolic.o ../../../../madness-git-naromero/src/madness/tensor/test_systolic.cc
In file included from ../../../../madness-git-naromero/src/madness/tensor/tensor.h:61:0,
                 from ../../../../madness-git-naromero/src/madness/tensor/test_systolic.cc:3:
../../../../madness-git-naromero/src/madness/tensor/tensoriter.h: In function ‘int main(int, char**)’:
../../../../madness-git-naromero/src/madness/tensor/tensoriter.h:265:26: warning: array subscript is above array bounds [-Warray-bounds]
                 dim[i-1] = dim[i];
                          ^
../../../../madness-git-naromero/src/madness/tensor/tensoriter.h:266:30: warning: array subscript is above array bounds [-Warray-bounds]
                 stride0[i-1] = stride0[i];
```

**Comment by naromero77** [comment]
For reference, this is the code. The comments indicate that prior compilers have emitted a warning.
            // Collapse stride and dimension info for remaining dimensions
            for (int i=jdim+1; i<=ndim; ++i) { // GCC COMPILER WARNING ... but need <= ... why?  
                dim[i-1] = dim[i];
                stride0[i-1] = stride0[i];
            }

**Comment by evaleev** [comment]
note "ndim--" on line 245 .. this should be OK, even though confuses static
analyzers

On Mon, Feb 15, 2016 at 5:00 PM, Nichols A. Romero <notifications@github.com
> wrote:

> For reference, this is the code. The comments indicate that prior
> compilers have emitted a warning.
> // Collapse stride and dimension info for remaining dimensions
> for (int i=jdim+1; i<=ndim; ++i) { // GCC COMPILER WARNING ... but need <=
> ... why?
>
> dim[i-1] = dim[i];
> stride0[i-1] = stride0[i];
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/178#issuecomment-184412929>
> .
>



-- 
web: valeyev.net

**Comment by naromero77** [comment]
I am less nervous now that you point that out. I think the compiler is just being conservative. I will close this issue tomorrow unless I hear a reply from others.

**Comment by robertjharrison** [comment]
The code is imperfect.  It seems to potentially (if ndim==MAXDIM) be
reading beyond the end of the array but is definitely only writing within
bounds.  I vaguely recall at one point inserting some fixup code so that we
could restrict the loop bound (i<=ndim) to (i<ndim) but that failed the
oldtensortest.  It occurs to me now that a "lazy" (and by at least one
metric virtuous, though quite shameful) fix would be to just dimension the
offfending array MAXDIM+1.

On Mon, Feb 15, 2016 at 5:20 PM, Nichols A. Romero <notifications@github.com
> wrote:

> I am less nervous now that you point that out. I think the compiler is
> just being conservative. I will close this issue tomorrow unless I hear a
> reply from others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/178#issuecomment-184420673>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262
