### ISSUE TITLE
compile-time warning of mra1.cc

### ISSUE THREAD

**Issue by naromero77** [m-a-d-n-e-s-s/madness#179]
Is this a real bug?

``` sh
make[4]: Entering directory `/home/naromero/madness-gcc-naromero/src/madness/mra'
/bin/sh ../../../libtool  --tag=CXX   --mode=compile mpicxx -DHAVE_CONFIG_H   -I../../../../madness-git-naromero/src -I../../../src -I../../../../madness-git-naromero/src/apps -DMRA_DATA_DIR=\"/home/naromero/madness-gcc-naromero/../madness-git-naromero/src/madness/mra\" -I/home/naromero/libxc-2.0.x/include -I/home/naromero/gperftools-2.2.1-GCC4.8.3/include  -DMPICH_SKIP_MPICXX=1 -DOMPI_SKIP_MPICXX=1  -O3 -std=c++11 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -g -Wall -Wno-strict-aliasing -Wno-deprecated -Wno-unused-local-typedefs -MT mra1.lo -MD -MP -MF .deps/mra1.Tpo -c -o mra1.lo ../../../../madness-git-naromero/src/madness/mra/mra1.cc
libtool: compile:  mpicxx -DHAVE_CONFIG_H -I../../../../madness-git-naromero/src -I../../../src -I../../../../madness-git-naromero/src/apps -DMRA_DATA_DIR=\"/home/naromero/madness-gcc-naromero/../madness-git-naromero/src/madness/mra\" -I/home/naromero/libxc-2.0.x/include -I/home/naromero/gperftools-2.2.1-GCC4.8.3/include -DMPICH_SKIP_MPICXX=1 -DOMPI_SKIP_MPICXX=1 -O3 -std=c++11 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -g -Wall -Wno-strict-aliasing -Wno-deprecated -Wno-unused-local-typedefs -MT mra1.lo -MD -MP -MF .deps/mra1.Tpo -c ../../../../madness-git-naromero/src/madness/mra/mra1.cc -o mra1.o
In file included from ../../../../madness-git-naromero/src/madness/tensor/tensor.h:56:0,
                 from ../../../../madness-git-naromero/src/madness/mra/mra.h:46,
                 from ../../../../madness-git-naromero/src/madness/mra/mra1.cc:32:
../../../../madness-git-naromero/src/madness/tensor/basetensor.h: In function 'madness::Tensor<typename madness::TensorResultType<leftT, rightT>::type> madness::general_transform(const madness::Tensor<T>&, const madness::Tensor<Q>*) [with T = std::complex<double>; Q = std::complex<double>; typename madness::TensorResultType<leftT, rightT>::type = std::complex<double>]':
../../../../madness-git-naromero/src/madness/tensor/basetensor.h:147:45: warning: array subscript is above array bounds [-Warray-bounds]
         long dim(int i) const {return _dim[i];}

In file included from ../../../../madness-git-naromero/src/madness/mra/mra.h:46:0,
                 from ../../../../madness-git-naromero/src/madness/mra/mra1.cc:32:
../../../../madness-git-naromero/src/madness/tensor/tensor.h:971:17: warning: '*((void*)& ind +24)' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 offset += i*_stride[d];
                 ^
```

**Comment by justusc** [comment]
It is hard to say. I think the error message you posted has output from one error message that is mixed with another. You may need to run it again with a single build thread to get a clean output.

**Comment by naromero77** [comment]
I was pretty sure I did this with a single build thread, but I will look
again.

On Wed, Feb 3, 2016 at 2:28 PM, Justus Calvin <notifications@github.com>
wrote:

> It is hard to say. I think the error message you posted has output from
> one error message that is mixed with another. You may need to run it again
> with a single build thread to get a clean output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/179#issuecomment-179445923>
> .
>



-- 
Nichols A. Romero, Ph.D.

**Comment by naromero77** [comment]
Here it is again:

[naromero@thing00 mra]$ make mra1.o
mpicxx -DHAVE_CONFIG_H   -I../../../../madness-git-naromero/src -I../../../src -I../../../../madness-git-naromero/src/apps -DMRA_DATA_DIR=\"/home/naromero/madness-gcc-naromero/../madness-git-naromero/src/madness/mra\" -I/home/naromero/libxc-2.0.x/include -I/home/naromero/gperftools-2.2.1-GCC4.8.3/include  -DMPICH_SKIP_MPICXX=1 -DOMPI_SKIP_MPICXX=1  -O3 -std=c++11 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -g -Wall -Wno-strict-aliasing -Wno-deprecated -Wno-unused-local-typedefs -MT mra1.o -MD -MP -MF .deps/mra1.Tpo -c -o mra1.o ../../../../madness-git-naromero/src/madness/mra/mra1.cc
In file included from ../../../../madness-git-naromero/src/madness/tensor/tensor.h:56:0,
                 from ../../../../madness-git-naromero/src/madness/mra/mra.h:46,
                 from ../../../../madness-git-naromero/src/madness/mra/mra1.cc:32:
../../../../madness-git-naromero/src/madness/tensor/basetensor.h: In function ‘madness::Tensor<typename madness::TensorResultType<leftT, rightT>::type> madness::general_transform(const madness::Tensor<T>&, const madness::Tensor<Q>*) [with T = std::complex<double>; Q = std::complex<double>; typename madness::TensorResultType<leftT, rightT>::type = std::complex<double>]’:
../../../../madness-git-naromero/src/madness/tensor/basetensor.h:147:45: warning: array subscript is above array bounds [-Warray-bounds]
         long dim(int i) const {return _dim[i];}
                                             ^
../../../../madness-git-naromero/src/madness/tensor/basetensor.h:147:45: warning: array subscript is above array bounds [-Warray-bounds]
         long dim(int i) const {return _dim[i];}
                                             ^
In file included from ../../../../madness-git-naromero/src/madness/mra/mra.h:46:0,
                 from ../../../../madness-git-naromero/src/madness/mra/mra1.cc:32:
../../../../madness-git-naromero/src/madness/tensor/tensor.h: In member function ‘void madness::FunctionImpl<T, NDIM>::plot_cube_kernel(madness::archive::archive_ptr<madness::Tensor<T> >, const keyT&, const coordT&, const coordT&, const std::vector<long int>&, bool) const [with T = double; long unsigned int NDIM = 1ul; madness::FunctionImpl<T, NDIM>::keyT = madness::Key<1ul>; madness::FunctionImpl<T, NDIM>::coordT = madness::Vector<double, 1ul>]’:
../../../../madness-git-naromero/src/madness/tensor/tensor.h:971:17: warning: ‘*((void*)& ind +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 offset += i*_stride[d];
