### ISSUE TITLE
can't compile testperiodic

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#180]
In line 400 in testperiodic.cc the const function "potential" is truncated, which I can't compile.

vector_complex_function_3d apply_potential(World& world, const real_function_3d& potential, const vector_complex_function_3d& psi)
{
    START_TIMER(world);
    potential.truncate(FunctionDefaults<3>::get_thresh()*0.1);
    auto vpsi = mul(world, potential, psi, false);
    world.gop.fence();
    END_TIMER(world, "apply potential");
    return vpsi;
}

/huge/flbi/build/2016-02-04--00-00-01_madness.git/madness.git/src/apps/moldft/testperiodic.cc:400:61: error: passing ‘const real_function_3d {aka const madness::Function<double, 3ul>}’ as ‘this’ argument of ‘madness::Function<T, NDIM>& madness::Function<T, NDIM>::truncate(double, bool) [with T = double; long unsigned int NDIM = 3ul]’ discards qualifiers [-fpermissive]

**Comment by justusc** [comment]
It looks like this error was introduced commit 61fa7db6e8dbc2378b50bfedf2acd5513211c0ed by @wsttiger. See the Travis build history. https://travis-ci.org/m-a-d-n-e-s-s/madness/builds/106545419

**Comment by wsttiger** [comment]
Sorry for the delay .... fixed!!
