### ISSUE TITLE
buglet during CMake build with 'make -j 8'

### ISSUE THREAD

**Issue by naromero77** [m-a-d-n-e-s-s/madness#184]
Hi,

Has anyone had this problem with building MADNESS with CMake:

You do:
make -j <N> where N is 8 (but it seems to be a problem with other values)

it builds 57% of the way and then it halts due to reasons that are unclear to me. Then you just do:
make -j <N> where N is 8

and it finishes to completion.

One thing that I find unusual is that I observe the following behaviour (even when I do make -j 4): it seems to build parts of Elemental, then it switches to building MADNESS for a while, then it switches back to building the rest of Elemental.

I am uploading my build script on BG/Q and my build log. I think the problem is coming from an external library, either libxc or Elemental, but I am not 100% sure.

I can work around the issue, but it would be a nuisance for a new user or a collaboration to have to restart the build midway through.

[bug.zip](https://github.com/m-a-d-n-e-s-s/madness/files/196482/bug.zip)

**Comment by naromero77** [comment]
I am hoping Justus has the cycles to take a look at this.

**Comment by justusc** [comment]
Unfortunately, I do not anticipate having any free time for the foreseeable future.

CMake makefiles are a little different than that of autotools. With autotools, make traverses the build tree one directory at a time. But CMake allows two directors to build concurrently. This is why you see it switching between Elemental and other parts of MADNESS. We might be able to define some artificial dependencies that forces the build order to be more like that of Autotools, but I would leave it alone unless it is causing problems. 

As for the first problem, I think it may be a bug in CMake. I have looked into it in the past, but never found a satisfactory answer. The best suggestion I can give you is to file a bug report with Kitware.

**Comment by naromero77** [comment]
Let me try to work on debugging it myself. If we come to the conclusion
that it is a CMake problem, I will file a bug with KitWare.

On Wednesday, March 30, 2016, Justus Calvin <notifications@github.com>
wrote:

> Unfortunately, I do not anticipate having any free time for the
> foreseeable future.
>
> CMake makefiles are a little different than that of autotools. With
> autotools, make traverses the build tree one directory at a time. But CMake
> allows two directors to build concurrently. This is why you see it
> switching between Elemental and other parts of MADNESS. We might be able to
> define some artificial dependencies that forces the build order to be more
> like that of Autotools, but I would leave it alone unless it is causing
> problems.
>
> As for the first problem, I think it may be a bug in CMake. I have looked
> into it in the past, but never found a satisfactory answer. The best
> suggestion I can give you is to file a bug report with Kitware.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/184#issuecomment-203654004>
>


-- 
Sent from Gmail Mobile

**Comment by hfp** [comment]
If your environment uses GNU Make 3.82 (or older), the issue might be related to GNU Make. Have a look at https://github.com/hfp/libxsmm/blob/master/Makefile#L4 (until line 14) to see my workaround (it's disabling parallel builds on this outdated/older toolchain). (and sorry for talking here, I am just watching this project ;-)

**Comment by jeffhammond** [comment]
@naromero77 Just file the bug with Kitware now and let them prove to you it is not their bug.  Given how shoddy CMake is, I don't know why you think it is anything else :-)

**Comment by naromero77** [comment]
The issues appears to be fixed in CMake 3.5.1, but required this commit as well

https://github.com/m-a-d-n-e-s-s/madness/commit/35d89c58e610b9123c8c532aabd0246a5b1b5399

Many thanks to Jack Poulson.

**Comment by naromero77** [comment]
Should we require CMake 3.5.1, or would this be too aggressive?

It seems to mostly affect people using Elemental, but perhaps it is affecting others.

**Comment by justusc** [comment]
I think requiring 3.5.1 would be too much too fast as it would prevent
people from run the CMake configuration.

We could place a warning in the CMake script about the bug than is
displayed if the CMake version is older than 3.5.1 and building Elemental.
The warning could also include guidance on how to work around it, and
instructions for installing a newer version of CMake (via the make file
provided by MADNESS).

On Apr 1, 2016, at 12:57 AM, Nichols A. Romero <notifications@github.com>
wrote:

Should we require CMake 3.5.1, or would this be too aggressive?

It seems to mostly affect people using Elemental, but perhaps it is
affecting others.

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub
<https://github.com/m-a-d-n-e-s-s/madness/issues/184#issuecomment-204248878>

**Comment by naromero77** [comment]
Sounds good.

For the sake of clarity, let me explain that there are two bugs:
1. If you do 'make -j N' where N is 8 or higher. The build breaks mid-way.
This seems to be independent of Elemental. If you just do 'make -j N' where
N is 4 or lower it seems to work fine.

2. If you upgrade to CMake 3.5.1, a bug in the Elemental CMake build system
is exposed. Why its not exposed with earlier CMake versions isn't clear to
me. If you don't fix the Elemental CMake problem, it doesn't even get
passed the initial configure.

I did not test intermediate version of CMake. The bug seems to exist with
CMake 3.3.0 and goes away with CMake 3.5.1, it may go away with one of the
3.4.x versions.




On Fri, Apr 1, 2016 at 6:58 AM, Justus Calvin <notifications@github.com>
wrote:

> I think requiring 3.5.1 would be too much too fast as it would prevent
> people from run the CMake configuration.
>
> We could place a warning in the CMake script about the bug than is
> displayed if the CMake version is older than 3.5.1 and building Elemental.
> The warning could also include guidance on how to work around it, and
> instructions for installing a newer version of CMake (via the make file
> provided by MADNESS).
>
> On Apr 1, 2016, at 12:57 AM, Nichols A. Romero <notifications@github.com>
> wrote:
>
> Should we require CMake 3.5.1, or would this be too aggressive?
>
> It seems to mostly affect people using Elemental, but perhaps it is
> affecting others.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/m-a-d-n-e-s-s/madness/issues/184#issuecomment-204248878
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/184#issuecomment-204368071>
>



-- 
Nichols A. Romero, Ph.D.

**Comment by naromero77** [comment]
I am considering this resolved.
https://github.com/m-a-d-n-e-s-s/madness/commit/cc957c787501512f9f47cdebba6a83235aebb16d
