### ISSUE TITLE
compiling with -DNDEBUG causes failure in transpose

### ISSUE THREAD

**Issue by naromero77** [m-a-d-n-e-s-s/madness#188]
Hi,

At first I thought this was a CMake issue, but it turns out that the difference arises in compiling the RELEASE version versus the RELWITHDEBINFO version which changes the compile flags. 

Question: Is this really a bug?

set(CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG" CACHE STRING "Inital C++ relea
se compile flags")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -Wall" CACHE STRING "Inital C++ relea
se with debug info compile flags")

Since I use to compile with -O3 under the autotools build system, by process of elimination I have to conclude that NDEBUG is causing this problem. 

This is error that I am seeing on a rather trivial moldft calculation:

screening parameters
 rhotol, rhomin 1.000000e-07 0.000000e+00
 sigtol, sigmin 1.000000e-10 1.000000e-10
         ggatol 1.000000e-04
    munge_ratio 1.000000e+01
polarized  false

TensorException: msg='TENSOR ASSERTION FAILED: "/home/naromero/madness-git-trunk/src/madness/tensor/tensor.h"(1950): t
anspose requires a matrix'
TensorException: msg='TENSOR ASSERTION FAILED: "/home/naromero/madness-git-trunk/src/madness/tensor/tensor.h"(1950): t
anspose requires a matrix'
                 failed assertion='t.ndim() == 2'
TensorException: msg='TENSOR ASSERTION FAILED: "/home/naromero/madness-git-trunk/src/madness/tensor/tensor.h"(1950): t
anspose requires a matrix'
                 failed assertion='t.ndim() == 2'
TensorException: msg='TENSOR ASSERTION FAILED: "/home/naromero/madness-git-trunk/src/madness/tensor/tensor.h"(1950): t
anspose requires a matrix'
                 value=-1
                 failed assertion='t.ndim() == 2'
                 failed assertion='t.ndim() == 2'
                 value=-1
                 value=-1
                 line=1950
                 line=1950
                 function='transpose'
                 value=-1
                 filename='/home/naromero/madness-git-trunk/src/madness/tensor/tensor.h'
                 line=1950
                 tensor=Tensor<double>(invalid_dimensions) at 0x0x19cecc06f8
                 function='transpose'
                 line=1950

                 function='transpose'

**Comment by naromero77** [comment]
It seems like it might be affecting the XML reader or even LibXC. The output line right above the aformentioned output is:
input line was:  lda
 1.000 Functional not found 
 1.000 Functional not found 
 
instead of:
input line was:  lda
 1.000 LDA_X 
 1.000 LDA_C_VWN 

with the RelDebInfo version (that runs correctly).

**Comment by justusc** [comment]
One other difference between release and relwithdebinfo is the level of optimization. -O3 vs -O2.

**Comment by justusc** [comment]
Also I don't see any occurrence of NDEBUG outside gtest.  It is possible that NDEBUG is used in the header of a dependence like LibXC, but it would certainly not affect the compiled external library. You could grep the public header files of LibXC to see if it is possible that NDEBUG is source of the error. Even if it is there it seems unlikely to cause such an error.

The level of optimization seem more likely to cause problems.

**Comment by naromero77** [comment]
I agree, except that I have been using -O3 without problems for a while.

The other difference I see is that one has '-g' and the other does not.

It such an old GCC compiler.... Another motivation to switch to Clang.

On Wednesday, April 6, 2016, Justus Calvin <notifications@github.com> wrote:

> Also I don't see any occurrence of NDEBUG outside gtest. It is possible
> that NDEBUG is used in the header of a dependence like LibXC, but it would
> certainly not affect the compiled external library. You could grep the
> public header files of LibXC to see if it is possible that NDEBUG is source
> of the error. Even if it is there it seems unlikely to cause such an error.
>
> The level of optimization seem more likely to cause problems.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/188#issuecomment-206360109>
>


-- 
Sent from Gmail Mobile

**Comment by naromero77** [comment]
For the BG/Q toolchains, there are four build options:
DEBUG
MINSIZEREL
RELEASE
RELWITHDEBINFO

Is there any issue with reducing it down to 1 option? Or would this break other things?

**Comment by justusc** [comment]
These are standard build options provided by CMake. If they are not defined in the toolchain, the defaults from CMake will be used. So you cannot get rid of them, but we are free to change the flags in these build options to whatever is appropriate.

I am not sure it is a good idea to reduce this down to a single set of flags. In most cases on BG/Q I expect we want release builds, but on rare occasions we do need debug and release w/ debug info builds to track down bugs. I realize there is something funky going on here. Perhaps we can experiment a bit to try and find the combination of flags that work best here?

**Comment by naromero77** [comment]
basically the flags for RELWITHDEBINFO work, but the ones for RELEASE lead to the tensor exception.

However, it is preferable to find the origin of this problem. It could just be a compiler bug, but source code error is usually the culprit.

Because of the C++ exceptions, I am not able to identify the MADNESS source file for the Tensor exception aposteriori from the core files.

Can CMake build system handle all the autotools options? For example, can I specify:
--enable-madex=abort

It does not look like it, based on the contents of Install_CMake.

**Comment by justusc** [comment]
> Can CMake build system handle all the autotools options? For example, can I specify:
> --enable-madex=abort
> 
> It does not look like it, based on the contents of Install_CMake.

See line 82 & 83 of `Install_CMake`

**Comment by naromero77** [comment]
wow... I totally missed that. Thanks

**Comment by naromero77** [comment]
I need a sanity check please! This is relevant part of the toolchain:

# Set compile flags
set(CMAKE_C_FLAGS_INIT             "-std=c99 -mcpu=a2 -mtune=a2" CACHE STRING "Inital C compile flags")
set(CMAKE_C_FLAGS_DEBUG            "-g -Wall" CACHE STRING "Inital C debug compile flags")
set(CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG" CACHE STRING "Inital C minimum size release compile flags")
set(CMAKE_C_FLAGS_RELEASE          "-O2 -g -Wall" CACHE STRING "Inital C release compile flags")
set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g -Wall" CACHE STRING "Inital C release with debug info compile flags")
set(CMAKE_CXX_FLAGS_INIT           "-std=c++11 -mcpu=a2 -mtune=a2" CACHE STRING "Inital C++ compile flags")
set(CMAKE_CXX_FLAGS_DEBUG          "-g -Wall" CACHE STRING "Inital C++ debug compile flags")
set(CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG" CACHE STRING "Inital C++ minimum size release compile flags")
set(CMAKE_CXX_FLAGS_RELEASE        "-O2 -g -Wall" CACHE STRING "Inital C++ release compile flags")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -Wall" CACHE STRING "Inital C++ release with debug info compile flags")


So, I purposely set the RELEASE and RELWITHDEBINFO compile flags equal to each other. RELEASE gives me the tensor exception while RELWITHDEBINFO does not. 

Each time I modify the toolchain I completely delete the build directory, run configure, and re-compile. I have repeated this twice because I am not above making dumb mistakes.

Now that I have set those compile flags to be equal, what is different? what am I missing?

**Comment by justusc** [comment]
Yes, you have the correct set of variables.

The build type you specify tells CMake which set of optimization flags to use when building targets. Since you have explicitly set these flags to be equal, there is no difference between the two.

**Comment by naromero77** [comment]
The binaries are not even the same size, so something is changing.

**Comment by justusc** [comment]
You can manually compare the compilation flags with

make VERBOSE=1

**Comment by naromero77** [comment]
That's equivalent to:
    -DCMAKE_VERBOSE_MAKEFILE=TRUE

right?

On Wed, Apr 6, 2016 at 4:54 PM, Justus Calvin <notifications@github.com>
wrote:

> You can manually compare the compilation flags with
>
> make VERBOSE=1
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/188#issuecomment-206587947>
>



-- 
Nichols A. Romero, Ph.D.

**Comment by naromero77** [comment]
So I see one buglet that explains the difference in binary sizes:

I think the intention was that RelWithDebInfo and Release have the same
assertion types. However, there is an inconsistency (or a typo) in the top
label CMakeLists.txt.

if (CMAKE_BUILD_TYPE STREQUAL Release OR
    CMAKE_BUILD_TYPE STREQUAL RelWithDebugInfo OR
    CMAKE_BUILD_TYPE STREQUAL MinSizeRel)
  set (DEFAULT_ASSERTION_TYPE "disable")
else ()
  set (DEFAULT_ASSERTION_TYPE "throw")
endif()

So the second OR in the condition should be RelWithDebInfo or
RelWithDebugInfo, alternatively the names of the compile flags in the
toolchain need to be corrected.

Let me know if you plan to fix it or if you want me to fix it. I believe
the fix should go in CMakeLists.txt.

Unfortunately, this only explains the differences in the binary. It doesn't
explain the origin of the Tensor Exception.


On Wed, Apr 6, 2016 at 5:08 PM, Nichols A. Romero <naromero@gmail.com>
wrote:

> That's equivalent to:
>     -DCMAKE_VERBOSE_MAKEFILE=TRUE
>
> right?
>
> On Wed, Apr 6, 2016 at 4:54 PM, Justus Calvin <notifications@github.com>
> wrote:
>
>> You can manually compare the compilation flags with
>>
>> make VERBOSE=1
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/m-a-d-n-e-s-s/madness/issues/188#issuecomment-206587947>
>>
>
>
>
> --
> Nichols A. Romero, Ph.D.
>
>


-- 
Nichols A. Romero, Ph.D.

**Comment by naromero77** [comment]
As far as I can tell, the problem is coming from LibXC. If you change the assertion type (MADNESS_ASSERT) to disabled, then LibXC cannot find the LDA functional which leads to the TENSOR_EXCEPTION.

**Comment by justusc** [comment]
I believe the correct name is RelWithDebInfo

**Comment by naromero77** [comment]
The problem manifests itself when the ASSERTION_TYPE is set to disable, and
it goes away when it set to throw or abort.

Laura has verified that this problem occurs on x86 desktop with GCC 4.9.0
and autotools.

Thus the problem is not: CMake, BG/Q, or any particular version of GCC.

I compiled with Clang on BG/Q and it core dumps here with signal 11
(invalid memory reference)
xcfunctional_libxc.cc:266

which is consistent with the problem I reported earlier in the thread: that
setting the ASSERTION_TYPE to disable seems to bork up LibXC. (it fails to
recognize the lda keyword from the input deck)

Can one of you C++ gurus take a look at XCfunctional::initialize?

It seems like we must be over-riding the stack somewhere to have such
erratic behaviour.


On Thu, Apr 7, 2016 at 7:25 AM, Justus Calvin <notifications@github.com>
wrote:

> I believe the correct name is RelWithDebInfo
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/188#issuecomment-206854018>
>



-- 
Nichols A. Romero, Ph.D.

**Comment by naromero77** [comment]
The problem persists if you remove LibXC from the equation.

Basically, to reproduce the problem you need to compile with the assertion
type equal to throw versus disable. Throw (the default under autotools)
seems to work, but disable (the default under CMake) leads to a Tensor
Exception, signal 11, or some other error very early on in the run.




On Thu, Apr 7, 2016 at 4:57 PM, Nichols A. Romero <naromero@gmail.com>
wrote:

> The problem manifests itself when the ASSERTION_TYPE is set to disable,
> and it goes away when it set to throw or abort.
>
> Laura has verified that this problem occurs on x86 desktop with GCC 4.9.0
> and autotools.
>
> Thus the problem is not: CMake, BG/Q, or any particular version of GCC.
>
> I compiled with Clang on BG/Q and it core dumps here with signal 11
> (invalid memory reference)
> xcfunctional_libxc.cc:266
>
> which is consistent with the problem I reported earlier in the thread:
> that setting the ASSERTION_TYPE to disable seems to bork up LibXC. (it
> fails to recognize the lda keyword from the input deck)
>
> Can one of you C++ gurus take a look at XCfunctional::initialize?
>
> It seems like we must be over-riding the stack somewhere to have such
> erratic behaviour.
>
>
> On Thu, Apr 7, 2016 at 7:25 AM, Justus Calvin <notifications@github.com>
> wrote:
>
>> I believe the correct name is RelWithDebInfo
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/m-a-d-n-e-s-s/madness/issues/188#issuecomment-206854018>
>>
>
>
>
> --
> Nichols A. Romero, Ph.D.
>
>


-- 
Nichols A. Romero, Ph.D.

**Comment by naromero77** [comment]
Closing this issue and opening another one that is more clear and concise.
