### ISSUE TITLE
graveyard file with no extension in tensor directory

### ISSUE THREAD

**Issue by naromero77** [m-a-d-n-e-s-s/madness#194]
Can this file be removed?
https://github.com/m-a-d-n-e-s-s/madness/blob/master/src/madness/tensor/graveyard

We will interpret silence, as approval to remove it.

**Comment by robertjharrison** [comment]
affirmative

On Thu, Jun 16, 2016 at 11:01 AM, Nichols A. Romero <
notifications@github.com> wrote:

> Can this file be removed?
>
> https://github.com/m-a-d-n-e-s-s/madness/blob/master/src/madness/tensor/graveyard
>
> We will interpret silence, as approval to remove it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/194>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHMgPcYTvmbMhMRELnPo-flHYBjp6WMpks5qMWVMgaJpZM4I3etB>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262
