### ISSUE TITLE
can't configure any more

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#205]
I can't configure madness neither on my mac nor on my cluster. Probably due to commit 624e824c933646f34344c6d9ef7caef13ab803f1, stating "cmake and autotools will die if TLS not found (as should always been)."

**Comment by evaleev** [comment]
please provide config.log (if using autotools) or CMakeFiles/CMakeOutput/Error.* (if cmaking).

**Comment by fbischoff** [comment]
mac:

[29.08.16 7:56] ./autogen.sh 
config/acx_check_tls.m4:61: error: m4_defn: undefined macro: _AC_LANG
../../lib/autoconf/lang.m4:115: AC_LANG_POP is expanded from...
config/acx_check_tls.m4:61: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1

linux:

[07:57] ./autogen.sh 
config/acx_check_tls.m4:59: error: m4_defn: undefined macro: _m4_divert_diversion
config/acx_check_tls.m4:59: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
