### ISSUE TITLE
PKG_CHECK_MODULES for PaRSEC

### ISSUE THREAD

**Issue by jeffhammond** [m-a-d-n-e-s-s/madness#206]
I don't know who added this but it breaks `./autogen.sh` along the lines of https://blogs.oracle.com/mandy/entry/autoconf_weirdness.

``` sh
       PKG_CHECK_MODULES([PaRSEC], [parsec],
                         [AC_DEFINE([HAVE_PARSEC], [1], [Define if have PaRSEC])
                          # Remove the trailing -I from the PaRSEC pkgconfig file
                          PaRSEC_CFLAGS=`echo ${PaRSEC_CFLAGS} | sed 's#-I$##'`
                          CFLAGS="$CFLAGS ${PaRSEC_CFLAGS}"
                          # Don't propagate the -std=c99 C flag to C++
                          PARSEC_CXXFLAGS=`echo ${PaRSEC_CFLAGS} | sed 's#-std=c99##'`
                          CXXFLAGS="$CXXFLAGS ${PARSEC_CXXFLAGS}"
                          LIBADD="$LIBADD ${PaRSEC_LIBS}"],
                         [with_parsec="no"])
```

And no, this is not a sign that Autotools sucks, it is a bug in the code.

**Comment by jeffhammond** [comment]
```sh
$ aclocal --version
aclocal (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

**Comment by justusc** [comment]
225c39773024cfb3011e9ddd426fd7f14943a399
@jeffhammond Blame is your friend.

**Comment by jeffhammond** [comment]
@evaleev Sorry, I forgot about the command `git blame`, although I assure you that blame is my friend :-)

@bosilca Fix your code :rage1:

**Comment by evaleev** [comment]
@jeffhammond what's the version of pkg-config that you have? from the link you provided it seems that it may be too old?

@bosilca @robertjharrison may be the easiest solution is to disable parsec from autotools build

**Comment by jeffhammond** [comment]
@evaleev 
```sh
$ pkg-config --version
0.23
```

**Comment by robertjharrison** [comment]
@bosilca @jeffhammond @evaleev The autoconf/aclocal versions are fine.  Now that we are checking using pkg-config people need to have it installed and the configure script needs to be modified to check and report a failure.  It seems to be installed on most systems (though one of the autoconf versions on dancer does not, so I built my own).   I think this is preferable to carrying our own version of pkg.m4.

@jeffhammond Jeff ... You will need to install the pkg-config package or set the AC_LOCAL_PATH to point to where pgk.m4 is installed.

**Comment by robertjharrison** [comment]
So it appears that aclocal is not finding the macro pkg.m4, so do the
following

ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh

replacing /usr/share with the path to where pkg.m4 is installed



On Mon, Aug 29, 2016 at 6:01 PM, Jeff Hammond <notifications@github.com>
wrote:
>
> @evaleev
>
> $ pkg-config --version
> 0.23
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
Robert J. Harrison
tel:  865-272-9262

**Comment by jeffhammond** [comment]
We apparently require a very recent `pkg-config`, one which is not supplied by default on KNL systems that run RHEL 7.1.  Hooray for breaking user experience!

```
pkg-config --version
0.27.1
```

```
uname -a
Linux bowman-lsm1 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
cat  /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```

**Comment by evaleev** [comment]
autotools build is not supported any longer
