### ISSUE TITLE
why are we using ${TBB_ROOT_DIR}/(lib/intel64/gcc4.4

### ISSUE THREAD

**Issue by jeffhammond** [m-a-d-n-e-s-s/madness#213]
# Cause

```sh
../INSTALL_CMake:      search path is ${TBB_ROOT_DIR}/(lib/intel64/gcc4.4|lib) on Linux and
../cmake/modules/FindTBB.cmake:      set(TBB_LIBRARY ${TBB_ROOT_DIR}/lib/intel64/gcc4.4;${TBB_ROOT_DIR}/lib 
../config/acx_with_tbb.m4:          LIBS="$LIBS -L$withval/lib/intel64/gcc4.4 -L$withval/lib"
```

# Effect

```sh
libtool: link: /opt/mpich/dev/gcc/default/bin/mpicxx -dynamiclib 
-Wl,-undefined -Wl,dynamic_lookup -o .libs/libMADtensor.0.dylib  
.libs/tensor.o .libs/tensoriter.o .libs/basetensor.o .libs/vmath.o   
-L/Users/jrhammon/Work/INTEL/MKL/libxsmm/lib -lxsmm -ltbb 
/Users/jrhammon/Work/MADNESS/libxc-gcc/lib/libxc.a -lprofiler 
-ltcmalloc -L/Users/jrhammon/Work/MADNESS/libxc-gcc/lib 
-L/usr/local/Cellar/tbb/4.4-20160526/lib/intel64/gcc4.4 
-L/usr/local/Cellar/tbb/4.4-20160526/lib 
-L/opt/intel//compilers_and_libraries_2017.0.102/mac/mkl/lib 
-lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lpthread -lm  
-O3 -march=native -Wl,-no_pie   
-install_name  /Users/jrhammon/Work/MADNESS/install-gcc/lib/libMADtensor.0.dylib 
-compatibility_version 1 -current_version 1.0 -Wl,-single_module
ld: warning: directory not found for option 
'-L/usr/local/Cellar/tbb/4.4-20160526/lib/intel64/gcc4.4'
```

# Details

I set the TBB directory like this:
```sh
--with-tbb=/usr/local/Cellar/tbb/4.4-20160526
```

The libraries are where I would expect them to be:
```sh
$ ls -1 /usr/local/Cellar/tbb/4.4-20160526/lib/*lib
/usr/local/Cellar/tbb/4.4-20160526/lib/libtbb.dylib
/usr/local/Cellar/tbb/4.4-20160526/lib/libtbbmalloc.dylib
/usr/local/Cellar/tbb/4.4-20160526/lib/libtbbmalloc_proxy.dylib
```

**Comment by evaleev** [comment]
A simple answer is TBB_ROOT_DIR is set by tbbvars.?sh

**Comment by justusc** [comment]
We are using that path because someone at Intel thought it would be a good idea to install the libraries in a nonstandard location. The Intel TBB source package doesn't provide a proper installation script either. All of this makes it difficult to guess where the library has been installed. So we error on the side of caution and include multiple paths. Home brew "manually" puts the library in the correct location.

The simplest workaround is to use the CMake config, which only uses the correct path.

**Comment by jeffhammond** [comment]
I guess this is the standalone TBB package that Intel ships, which I never use because it comes with the Intel compiler.  The version Intel ships is identical to the OSS version, so it surprises me that anyone is taking the time to register to download the Intel binary rather that installing the OSS version.

Anyways, this makes sense and I will not worry about it anymore and fantasize about some day fixing the configure test for this.
