### ISSUE TITLE
libtool: Version mismatch error.  This is libtool 2.4.4, but the definition of this LT_INIT comes from libtool 2.4.2.

### ISSUE THREAD

**Issue by jeffhammond** [m-a-d-n-e-s-s/madness#215]
Solution described in http://stackoverflow.com/questions/3096989/libtool-version-mismatch-error.  

I will fix this shortly but want an issue to track it.

**Comment by sohail0992** [comment]
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[2]: *** [] Error 63
