### ISSUE TITLE
Autotools build does not create CMake version file

### ISSUE THREAD

**Issue by mbanck** [m-a-d-n-e-s-s/madness#225]
If I build MADNESS with autotools, ```config/madness-config.cmake``` gets created and installed, but no accompanying version file. That one only gets created for CMake build it seems (in ```CMakeLists.txt:540```). So building MADNESS with autotools and then using the result with CMake does not seem to work at the moment, unless I am missing something?

**Comment by robertjharrison** [comment]
You are correct.  You cannot mix cmake and autotools.

**Comment by evaleev** [comment]
-version file added, but the autotools-based madness does not produce useful cmake config files and thus cmake-based madness build should be used if further integration of madness with cmake packages is desired.

**Comment by mbanck** [comment]
By the way, I've noticed that the reverse is true as well: the CMake build does not create/install the MADNESS.pc pkgconfig file.
