### ISSUE TITLE
Error in CC2::solve_cc2

### ISSUE THREAD

**Issue by justusc** [m-a-d-n-e-s-s/madness#227]
This looks like an error to me.

```
/Users/justus2/Developer/src/madness/src/apps/chem/CC2.cc:250:10: warning: taking the absolute value of unsigned type 'bool' has no effect [-Wabsolute-value]
      if(fabs(delta_correlation>parameters.econv)) energy_converged = false;
         ^
/Users/justus2/Developer/src/madness/src/apps/chem/CC2.cc:250:10: note: remove the call to 'fabs' since unsigned values cannot be negative
      if(fabs(delta_correlation>parameters.econv)) energy_converged = false;
         ^~~~
/Users/justus2/Developer/src/madness/src/apps/chem/CC2.cc:250:10: warning: implicit conversion turns floating-point number into bool: 'double' to 'bool' [-Wimplicit-conversion-floating-point-to-bool]
      if(fabs(delta_correlation>parameters.econv)) energy_converged = false;
      ~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kottmanj** [comment]
Thanks for notifying. We are preparing a pull request with the current 
CC2 where the issue is fixed.

Best,

Jakob



Am 01/01/17 um 20:33 schrieb Justus Calvin:
> This looks like an error to me.
>
> ```
> /Users/justus2/Developer/src/madness/src/apps/chem/CC2.cc:250:10: warning: taking the absolute value of unsigned type 'bool' has no effect [-Wabsolute-value]
>        if(fabs(delta_correlation>parameters.econv)) energy_converged = false;
>           ^
> /Users/justus2/Developer/src/madness/src/apps/chem/CC2.cc:250:10: note: remove the call to 'fabs' since unsigned values cannot be negative
>        if(fabs(delta_correlation>parameters.econv)) energy_converged = false;
>           ^~~~
> /Users/justus2/Developer/src/madness/src/apps/chem/CC2.cc:250:10: warning: implicit conversion turns floating-point number into bool: 'double' to 'bool' [-Wimplicit-conversion-floating-point-to-bool]
>        if(fabs(delta_correlation>parameters.econv)) energy_converged = false;
>        ~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
>
