### ISSUE TITLE
Travis-CI Mac OSX build failures

### ISSUE THREAD

**Issue by bsundahl** [m-a-d-n-e-s-s/madness#280]
The last three pull requests have all failed on the OSX build tests inside Travis-CI. I am looking through the build logs and all three are failing when running dep-$TRAVIS_OS_NAME.sh. More specifically, the build fails when trying to install the dependencies of TBB (the failing dependency is python@2.)

Can someone with more Travis-CI gumption please take a look at this? Possibly Ed?

**Comment by jeffhammond** [comment]
Switch to Python 3.

**Comment by evaleev** [comment]
fixed by 13839b4d539b40feb00d0acdba478b4dc5f1a519
