### ISSUE TITLE
mkl configuration 

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#30]
The current MKL configuration seems to work only with recent MKL versions. Older MKL has the path
$MKLROOT/lib/em64t/
while more recent version have
$MKLROOT/lib/intel64/
Since "intel64" is hard-wired one has to specify the real MKL paths while unsetting mkl '--enable-mkl=no',

**Comment by jeffhammond** [comment]
Also, within the autotools environment, it's pretty easy to test for a variety of paths until the MKL symbols are found.
