### ISSUE TITLE
test_future hangs on mac

### ISSUE THREAD

**Issue by fbischoff** [m-a-d-n-e-s-s/madness#31]
On my MBP (OS X 10.9.4, compiler: clang) test_future hangs:
MADNESS runtime initialized with 3 threads in the pool and affinity -1 -1 -1
IN Q 1
IN STEAL
Stealing 0x1006020f0

On my linux machine it works:
MADNESS runtime initialized with 7 threads in the pool and affinity -1 -1 -1
IN Q 0
Helloab donea

**Comment by justusc** [comment]
This issue was resolved a while ago.
