### ISSUE TITLE
Error when defining libxc functionals in moldft

### ISSUE THREAD

**Issue by lratcliff** [m-a-d-n-e-s-s/madness#325]
I'm having problems defining a libxc input string in moldft.  For example if I use the following input file:

dft
  xc gga_x_pbe 1.0 gga_c_pbe 1.0
end
geometry
  He 0.0 0.0 0.0
end

Then I get the error:
found an error for key >> xc << 
trailing characters in arguement >> gga_x_pbe 1.0 gga_c_pbe 1.0 <<

I'm not sure if I'm missing something about the new input class, but it seems like it's not designed to handle input strings with spaces in.  I think libxc strings are the only place where this poses a problem.

**Comment by fbischoff** [comment]
fixed by commit 322f8455

**Comment by fbischoff** [comment]
By the way: There a few xc functional predefined in the code (xcfunctional_libxc.cc:84): lda, bp86, pbe, pbe0, b3lyp, which you can use directly, e.g. 
xc pbe




Florian Bischoff
Humboldt-Universitaet zu Berlin, Institut fuer Chemie
Unter den Linden 6, 10099 Berlin
phone: +49-30-2093-7140
florian.bischoff@hu-berlin.de

**Comment by lratcliff** [comment]
Thanks, and that's really useful to know.
