### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by josephjohnjj** [m-a-d-n-e-s-s/madness#330]
I tried to build madness but i get the following error

/home/joseph/madness/madness/src/apps/chem/zcis.cc:132:10: error: expected unqualified-id before ‘[’ token
     auto [atmp, rest] = split(newx,thisroot.afunction.size());
          ^
/home/joseph/madness/madness/src/apps/chem/zcis.cc:133:10: error: expected unqualified-id before ‘[’ token
     auto [btmp, rest2] = split(rest,thisroot.bfunction.size());
          ^
/home/joseph/madness/madness/src/apps/chem/zcis.cc:134:10: error: ‘rest2’ was not declared in this scope
     newx=rest2;
          ^~~~~
/home/joseph/madness/madness/src/apps/chem/zcis.cc:135:24: error: ‘atmp’ was not declared in this scope
     thisroot.afunction=atmp;
                        ^~~~
/home/joseph/madness/madness/src/apps/chem/zcis.cc:136:24: error: ‘btmp’ was not declared in this scope
     thisroot.bfunction=btmp;
                        ^~~~
/home/joseph/madness/madness/src/apps/chem/zcis.cc: In member function ‘std::vector<madness::Function<std::complex<double>, 3ul> > madness::Zcis::compute_residuals(madness::Zcis::root&) const’:
/home/joseph/madness/madness/src/apps/chem/zcis.cc:278:7: error: expected unqualified-id before ‘[’ token
  auto [atmp, btmp] = split(tmp0,root.afunction.size());
       ^
/home/joseph/madness/madness/src/apps/chem/zcis.cc:279:49: error: ‘atmp’ was not declared in this scope
  std::vector<complex_function_3d> tmp=append(Qa(atmp),Qb(btmp));
                                                 ^~~~
/home/joseph/madness/madness/src/apps/chem/zcis.cc:279:58: error: ‘btmp’ was not declared in this scope
  std::vector<complex_function_3d> tmp=append(Qa(atmp),Qb(btmp));
                                                          ^~~~
src/apps/chem/CMakeFiles/MADchem-obj.dir/build.make:348: recipe for target 'src/apps/chem/CMakeFiles/MADchem-obj.dir/zcis.cc.o' failed
make[2]: *** [src/apps/chem/CMakeFiles/MADchem-obj.dir/zcis.cc.o] Error 1
CMakeFiles/Makefile2:4152: recipe for target 'src/apps/chem/CMakeFiles/MADchem-obj.dir/all' failed
make[1]: *** [src/apps/chem/CMakeFiles/MADchem-obj.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fbischoff** [comment]
The syntax is supported from C++17 (I think), so just set the C++ standard accordingly

Best,
Florian


Florian Bischoff
Humboldt-Universitaet zu Berlin, Institut fuer Chemie
Unter den Linden 6, 10099 Berlin
phone: +49-30-2093-7140
florian.bischoff@hu-berlin.de

**Comment by evaleev** [comment]
The default should be changed to 17 then if there is code that uses it.

**Comment by josephjohnjj** [comment]
I set the C++ standard to 17 ( I used set(CMAKE_CXX_STANDARD 17)) but the error still persists.

**Comment by evaleev** [comment]
Which compiler version are you using? Would you please report the actual
compiler invocation?

**Comment by kottmanj** [comment]
Hi Joseph,

If it helps you, you can have a look at the ci tests here:
https://github.com/m-a-d-n-e-s-s/madness/blob/master/ci/build-linux.sh
(see here which compilers are used: https://github.com/m-a-d-n-e-s-s/madness/blob/master/ci/dep-linux.sh)
The tests are currently performed with gcc-8 and mpich, so this combination should work

Here are some builds which currently work for me:
gcc-7 with mpich:
mpicxx --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

gcc-7 with openmpi (3.1.1)
mpicxx --version
g++ (GCC) 7.3.0

intel with intel-mpi
mpicxx --version
icc (ICC) 18.0.2 20180210

intel with openmpi (3.1.1)
mpicxx --version
icpc (ICC) 18.0.3 20180410

manually setting the flag for c++17 was not necessary in all cases

Some pitfalls I experienced in the past:
- make sure that the mpi compiler is linked against the right c++ compiler
- If you reconfigure with cmake, better remove the whole build directory beforehand
- if the links for the compilers are not set correctly on your system/cluster you can set the compilers with the corresponding cmake flags, like:
-D CMAKE_CXX_COMPILER=/usr/bin/g++-8 -D MPI_CXX_COMPILER=/usr/bin/mpicxx

**Comment by josephjohnjj** [comment]
I am using gcc version 6.5.0. The actual invocation is as follows:

[ 46%] Building CXX object src/apps/chem/CMakeFiles/MADchem-obj.dir/zcis.cc.o
cd /home/joseph/madness/build/src/apps/chem && /usr/bin/g++  -DMAD_ROOT_DIR=\"/home/joseph/madness/madness\" -DMPICH_SKIP_MPICXX=1 -DMRA_CHEMDATA_DIR=\"/home/joseph/madness/madness/src/apps/chem\" -DOMPI_SKIP_MPICXX=1 -I/home/joseph/madness/build/src/apps/chem -I/home/joseph/madness/madness/src/apps/chem -I/home/joseph/madness/madness/src -I/home/joseph/madness/build/src -I/home/joseph/madness/madness/src/apps -I/home/joseph/madness/build/src/madness/mra -I/home/joseph/madness/madness/src/madness/mra -I/home/joseph/madness/build/src/madness/tensor -I/home/joseph/madness/madness/src/madness/tensor -I/home/joseph/madness/build/src/madness/misc -I/home/joseph/madness/madness/src/madness/misc -I/home/joseph/madness/build/src/madness/world -I/home/joseph/madness/madness/src/madness/world -I/home/joseph/madness/build/src/madness/external/tinyxml -I/home/joseph/madness/madness/src/madness/external/tinyxml -I/home/joseph/madness/build/src/madness/external/muParser -I/home/joseph/madness/madness/src/madness/external/muParser  -std=c++1z -fPIC   -std=c++1z -o CMakeFiles/MADchem-obj.dir/zcis.cc.o -c /home/joseph/madness/madness/src/apps/chem/zcis.cc

**Comment by evaleev** [comment]
@josephjohnjj gcc 6 does not fully support c++17. See https://gcc.gnu.org/projects/cxx-status.html . Your issue is the lack of support of structured bindings by gcc 6.5.0. Please upgrade the compiler.
