### ISSUE TITLE
The 'install' target is broken:  "/usr/ports/science/madness/work/.build/src/madness/mra/mraplot": No such   file or directory.

### ISSUE THREAD

**Issue by yurivict** [m-a-d-n-e-s-s/madness#341]
```
CMake Error at src/madness/mra/cmake_install.cmake:137 (file):
  file INSTALL cannot find
  "/usr/ports/science/madness/work/.build/src/madness/mra/mraplot": No such
  file or directory.
Call Stack (most recent call first):
  src/madness/cmake_install.cmake:69 (include)
  src/cmake_install.cmake:41 (include)
  cmake_install.cmake:86 (include)
```

Rev. 35077935

**Comment by yurivict** [comment]
cmake/modules/AddMADExecutable.cmake seems to be broken when ```BUILD_SHARED_LIBS=ON```. It doesn't build executables in such case.

**Comment by SabariKumar** [comment]
I'm also getting the same error with an identical call stack, on Ubuntu 18.04 using gcc 7.5.0, g++ 7.5.0

**Comment by yurivict** [comment]
@evaleev 

Hi, Any chance to fix this?

Thanks.
Yuri

**Comment by robertjharrison** [comment]
Fixed (though you have to do make everything followed by make install)

**Comment by Pro-pra** [comment]
i compile latest git version, and problem present! 
files from app and examples dir not compile
