### ISSUE TITLE
Rengineering of the TBB code -- Status of TBB on BGQ?

### ISSUE THREAD

**Issue by wsttiger** [m-a-d-n-e-s-s/madness#52]
Jeff: I know of no issues but testing is quite limited.  I recall the TBB test suite passes except for GUI stuff though.  Testing with MADNESS is essential for moving forward here.

**Comment by naromero77** [comment]
The solution here is to document current short comings in the TBB bg_iron.inc makefile (e.g. no libtbbmalloc_proxy.a ) and point them to Jeff's github site. I am assuming Jeff is alright with the latter?

**Comment by jeffhammond** [comment]
You can point people to my Github fork.  I'll not remove it without notice.

**Comment by justusc** [comment]
We could also move fork to the M-A-D-N-E-S-S organization or fork the fork, if we fell that is a better solution or Jeff no longer wants to maintain it.

**Comment by jeffhammond** [comment]
That's a great idea. I'll put a copy of TBB on our org page.

On Wednesday, February 18, 2015, Justus Calvin <notifications@github.com>
wrote:

> We could also move fork to the M-A-D-N-E-S-S organization or fork the
> fork, if we fell that is a better solution or Jeff no longer wants to
> maintain it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/issues/52#issuecomment-74886914>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/
