### ISSUE TITLE
Do we need to include -lgfortran on link line with MKL?

### ISSUE THREAD

**Issue by wsttiger** [m-a-d-n-e-s-s/madness#60]

**Comment by justusc** [comment]
I believe the answer, in general, is no. I think it was required in older versions, but the current MKL link advisor does not include it. However, if someone has a problem with this, submit a new issue and we can fix it.

**Comment by jeffhammond** [comment]
In my opinion, this sort of issue should always be addressed with build documentation rather than configure.  It is not too much to ask for people to set LDFLAGS when necessary.

**Comment by justusc** [comment]
One of our goals is to improve configure so that users need to specify as few flags as possible. We obviously cannot get everything, but we want to include some of the more common options.
